// Clinical Diagnostic Panel: Complete Thyroid Function & Autoantibody Panel
// Laboratory Department: Endocrinology | Automated Quality Assurance

export interface LabPanelAnalyte {
  analyteCode: string;
  analyteName: string;
  measurementUnits: string;
  referenceInterval: string;
  criticalLowThreshold?: number;
  criticalHighThreshold?: number;
  deltaCheckTolerancePercent: number;
  specimenStabilityHoursRoomTemp: number;
  interferingSubstances: string[];
  clinicalInterpretationGuide: string;
}

export const THYROID_AXIS_ANALYTES: LabPanelAnalyte[] = [
  {
    analyteCode: 'ANL-THYR-01',
    analyteName: 'Endocrinology Serum Marker 01',
    measurementUnits: 'mmol/L',
    referenceInterval: '1.5 - 14.0',
    criticalLowThreshold: 0.8,
    criticalHighThreshold: 31.5,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-02',
    analyteName: 'Endocrinology Serum Marker 02',
    measurementUnits: 'ng/mL',
    referenceInterval: '3.0 - 18.0',
    criticalLowThreshold: 1.6,
    criticalHighThreshold: 38.0,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-03',
    analyteName: 'Endocrinology Serum Marker 03',
    measurementUnits: 'mg/dL',
    referenceInterval: '4.5 - 22.0',
    criticalLowThreshold: 2.4,
    criticalHighThreshold: 44.5,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-04',
    analyteName: 'Endocrinology Serum Marker 04',
    measurementUnits: 'mmol/L',
    referenceInterval: '6.0 - 26.0',
    criticalLowThreshold: 3.2,
    criticalHighThreshold: 51.0,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-05',
    analyteName: 'Endocrinology Serum Marker 05',
    measurementUnits: 'ng/mL',
    referenceInterval: '7.5 - 30.0',
    criticalLowThreshold: 4.0,
    criticalHighThreshold: 57.5,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-06',
    analyteName: 'Endocrinology Serum Marker 06',
    measurementUnits: 'mg/dL',
    referenceInterval: '9.0 - 34.0',
    criticalLowThreshold: 4.8,
    criticalHighThreshold: 64.0,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-07',
    analyteName: 'Endocrinology Serum Marker 07',
    measurementUnits: 'mmol/L',
    referenceInterval: '10.5 - 38.0',
    criticalLowThreshold: 5.6,
    criticalHighThreshold: 70.5,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-08',
    analyteName: 'Endocrinology Serum Marker 08',
    measurementUnits: 'ng/mL',
    referenceInterval: '12.0 - 42.0',
    criticalLowThreshold: 6.4,
    criticalHighThreshold: 77.0,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-09',
    analyteName: 'Endocrinology Serum Marker 09',
    measurementUnits: 'mg/dL',
    referenceInterval: '13.5 - 46.0',
    criticalLowThreshold: 7.2,
    criticalHighThreshold: 83.5,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-10',
    analyteName: 'Endocrinology Serum Marker 10',
    measurementUnits: 'mmol/L',
    referenceInterval: '15.0 - 50.0',
    criticalLowThreshold: 8.0,
    criticalHighThreshold: 90.0,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-11',
    analyteName: 'Endocrinology Serum Marker 11',
    measurementUnits: 'ng/mL',
    referenceInterval: '16.5 - 54.0',
    criticalLowThreshold: 8.8,
    criticalHighThreshold: 96.5,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-12',
    analyteName: 'Endocrinology Serum Marker 12',
    measurementUnits: 'mg/dL',
    referenceInterval: '18.0 - 58.0',
    criticalLowThreshold: 9.6,
    criticalHighThreshold: 103.0,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-13',
    analyteName: 'Endocrinology Serum Marker 13',
    measurementUnits: 'mmol/L',
    referenceInterval: '19.5 - 62.0',
    criticalLowThreshold: 10.4,
    criticalHighThreshold: 109.5,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-14',
    analyteName: 'Endocrinology Serum Marker 14',
    measurementUnits: 'ng/mL',
    referenceInterval: '21.0 - 66.0',
    criticalLowThreshold: 11.2,
    criticalHighThreshold: 116.0,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
  {
    analyteCode: 'ANL-THYR-15',
    analyteName: 'Endocrinology Serum Marker 15',
    measurementUnits: 'mg/dL',
    referenceInterval: '22.5 - 70.0',
    criticalLowThreshold: 12.0,
    criticalHighThreshold: 122.5,
    deltaCheckTolerancePercent: 20.0,
    specimenStabilityHoursRoomTemp: 8,
    interferingSubstances: ['Gross hemolysis (H-index > 150)', 'Severe lipemia (L-index > 300)', 'Icterus'],
    clinicalInterpretationGuide: 'Marker elevation indicates endocrinology parenchymal cellular injury or altered physiological clearance.',
  },
];

export function getThyroidAxisAnalyte(code: string): LabPanelAnalyte | undefined {
  return THYROID_AXIS_ANALYTES.find((a) => a.analyteCode === code);
}
