// ICD-10 WHO Standard Chapter X: Diseases of the Respiratory System
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_X_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'X00.1',
    snomedCode: '323738843',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 001',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X00.2',
    snomedCode: '345400842',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 002',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X00.3',
    snomedCode: '316949348',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 003',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X00.4',
    snomedCode: '328745153',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 004',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X00.5',
    snomedCode: '351416918',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 005',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X00.6',
    snomedCode: '317696246',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 006',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X00.7',
    snomedCode: '357696765',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 007',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X00.8',
    snomedCode: '358897933',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 008',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X00.9',
    snomedCode: '330905203',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 009',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X01.0',
    snomedCode: '359486741',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 010',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X01.1',
    snomedCode: '323801078',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 011',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X01.2',
    snomedCode: '351773829',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 012',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X01.3',
    snomedCode: '338408346',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 013',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X01.4',
    snomedCode: '311801747',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 014',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X01.5',
    snomedCode: '326504858',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 015',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X01.6',
    snomedCode: '332479152',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 016',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X01.7',
    snomedCode: '358765734',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 017',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X01.8',
    snomedCode: '328996572',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 018',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X01.9',
    snomedCode: '322964377',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 019',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X02.0',
    snomedCode: '323619872',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 020',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X02.1',
    snomedCode: '378804286',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 021',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X02.2',
    snomedCode: '329494769',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 022',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X02.3',
    snomedCode: '333322676',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 023',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X02.4',
    snomedCode: '320140665',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 024',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X02.5',
    snomedCode: '365446755',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 025',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X02.6',
    snomedCode: '330130439',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 026',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X02.7',
    snomedCode: '336039141',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 027',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X02.8',
    snomedCode: '359215031',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 028',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X02.9',
    snomedCode: '374320469',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 029',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X03.0',
    snomedCode: '308933290',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 030',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X03.1',
    snomedCode: '376575403',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 031',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X03.2',
    snomedCode: '345140088',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 032',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X03.3',
    snomedCode: '331844519',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 033',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X03.4',
    snomedCode: '377371961',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 034',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X03.5',
    snomedCode: '361799326',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 035',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X03.6',
    snomedCode: '324716851',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 036',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X03.7',
    snomedCode: '304153459',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 037',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X03.8',
    snomedCode: '312897540',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 038',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X03.9',
    snomedCode: '319307258',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 039',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X04.0',
    snomedCode: '325632059',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 040',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X04.1',
    snomedCode: '332259186',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 041',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X04.2',
    snomedCode: '332223237',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 042',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X04.3',
    snomedCode: '353631560',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 043',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X04.4',
    snomedCode: '311620839',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 044',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
  {
    icd10Code: 'X04.5',
    snomedCode: '365970824',
    termTitle: 'Diseases of the Respiratory System Clinical Entity Variant 045',
    clinicalCategory: 'Pulmonology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the respiratory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Pulmonology physician upon escalation.',
  },
];

export function getChapterXByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_X_CATALOG.find((entry) => entry.icd10Code === code);
}
