// ICD-10 WHO Standard Chapter IV: Endocrine, Nutritional and Metabolic Diseases
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_IV_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'IV00.1',
    snomedCode: '367267444',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 001',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV00.2',
    snomedCode: '351910056',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 002',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV00.3',
    snomedCode: '324248893',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 003',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV00.4',
    snomedCode: '347603738',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 004',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV00.5',
    snomedCode: '362482758',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 005',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV00.6',
    snomedCode: '368972751',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 006',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV00.7',
    snomedCode: '323590431',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 007',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV00.8',
    snomedCode: '364920665',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 008',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV00.9',
    snomedCode: '331602143',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 009',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV01.0',
    snomedCode: '337332953',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 010',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV01.1',
    snomedCode: '361842953',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 011',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV01.2',
    snomedCode: '357303962',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 012',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV01.3',
    snomedCode: '347890208',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 013',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV01.4',
    snomedCode: '344141679',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 014',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV01.5',
    snomedCode: '342268694',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 015',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV01.6',
    snomedCode: '334648850',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 016',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV01.7',
    snomedCode: '323193202',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 017',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV01.8',
    snomedCode: '335311612',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 018',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV01.9',
    snomedCode: '335943932',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 019',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV02.0',
    snomedCode: '347742936',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 020',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV02.1',
    snomedCode: '305341860',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 021',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV02.2',
    snomedCode: '377032173',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 022',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV02.3',
    snomedCode: '302643027',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 023',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV02.4',
    snomedCode: '349462123',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 024',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV02.5',
    snomedCode: '375509430',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 025',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV02.6',
    snomedCode: '336292272',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 026',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV02.7',
    snomedCode: '312498902',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 027',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV02.8',
    snomedCode: '365026033',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 028',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV02.9',
    snomedCode: '366637361',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 029',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV03.0',
    snomedCode: '374727607',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 030',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV03.1',
    snomedCode: '323917821',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 031',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV03.2',
    snomedCode: '358849388',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 032',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV03.3',
    snomedCode: '373323002',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 033',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV03.4',
    snomedCode: '366324281',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 034',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV03.5',
    snomedCode: '342113303',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 035',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV03.6',
    snomedCode: '308764872',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 036',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV03.7',
    snomedCode: '355479219',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 037',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV03.8',
    snomedCode: '363594612',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 038',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV03.9',
    snomedCode: '358629802',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 039',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV04.0',
    snomedCode: '363747976',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 040',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV04.1',
    snomedCode: '358900502',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 041',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV04.2',
    snomedCode: '345756226',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 042',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV04.3',
    snomedCode: '321554550',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 043',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV04.4',
    snomedCode: '367533802',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 044',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
  {
    icd10Code: 'IV04.5',
    snomedCode: '325566636',
    termTitle: 'Endocrine, Nutritional and Metabolic Diseases Clinical Entity Variant 045',
    clinicalCategory: 'Endocrinology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for endocrine, nutritional and metabolic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Endocrinology physician upon escalation.',
  },
];

export function getChapterIVByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_IV_CATALOG.find((entry) => entry.icd10Code === code);
}
