// ICD-10 WHO Standard Chapter XIX: Injury, Poisoning and Certain Other Consequences of External Causes
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_XIX_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'XIX00.1',
    snomedCode: '354021111',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 001',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX00.2',
    snomedCode: '349028867',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 002',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX00.3',
    snomedCode: '324957590',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 003',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX00.4',
    snomedCode: '327511460',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 004',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX00.5',
    snomedCode: '334688832',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 005',
    clinicalCategory: 'Trauma',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX00.6',
    snomedCode: '355371423',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 006',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX00.7',
    snomedCode: '373051603',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 007',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX00.8',
    snomedCode: '378085795',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 008',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX00.9',
    snomedCode: '307128472',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 009',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX01.0',
    snomedCode: '361712043',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 010',
    clinicalCategory: 'Trauma',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX01.1',
    snomedCode: '359445171',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 011',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX01.2',
    snomedCode: '318591003',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 012',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX01.3',
    snomedCode: '365379252',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 013',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX01.4',
    snomedCode: '330962901',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 014',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX01.5',
    snomedCode: '322049236',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 015',
    clinicalCategory: 'Trauma',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX01.6',
    snomedCode: '337655347',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 016',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX01.7',
    snomedCode: '324732883',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 017',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX01.8',
    snomedCode: '373201379',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 018',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX01.9',
    snomedCode: '357087789',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 019',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX02.0',
    snomedCode: '346118798',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 020',
    clinicalCategory: 'Trauma',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX02.1',
    snomedCode: '324177549',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 021',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX02.2',
    snomedCode: '331685003',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 022',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX02.3',
    snomedCode: '328929322',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 023',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX02.4',
    snomedCode: '367626912',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 024',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX02.5',
    snomedCode: '360156958',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 025',
    clinicalCategory: 'Trauma',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX02.6',
    snomedCode: '373671057',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 026',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX02.7',
    snomedCode: '378417326',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 027',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX02.8',
    snomedCode: '312535878',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 028',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX02.9',
    snomedCode: '347257261',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 029',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX03.0',
    snomedCode: '350104792',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 030',
    clinicalCategory: 'Trauma',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX03.1',
    snomedCode: '367859280',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 031',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX03.2',
    snomedCode: '321717877',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 032',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX03.3',
    snomedCode: '360074075',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 033',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX03.4',
    snomedCode: '363017279',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 034',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX03.5',
    snomedCode: '350790517',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 035',
    clinicalCategory: 'Trauma',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX03.6',
    snomedCode: '341969270',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 036',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX03.7',
    snomedCode: '307388505',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 037',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX03.8',
    snomedCode: '302382218',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 038',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX03.9',
    snomedCode: '343461122',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 039',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX04.0',
    snomedCode: '333969714',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 040',
    clinicalCategory: 'Trauma',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX04.1',
    snomedCode: '348473245',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 041',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX04.2',
    snomedCode: '309183206',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 042',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX04.3',
    snomedCode: '378539641',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 043',
    clinicalCategory: 'Trauma',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX04.4',
    snomedCode: '353182549',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 044',
    clinicalCategory: 'Trauma',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
  {
    icd10Code: 'XIX04.5',
    snomedCode: '334538859',
    termTitle: 'Injury, Poisoning and Certain Other Consequences of External Causes Clinical Entity Variant 045',
    clinicalCategory: 'Trauma',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for injury, poisoning and certain other consequences of external causes with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Trauma physician upon escalation.',
  },
];

export function getChapterXIXByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_XIX_CATALOG.find((entry) => entry.icd10Code === code);
}
