// ICD-10 WHO Standard Chapter XX: External Causes of Morbidity
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_XX_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'XX00.1',
    snomedCode: '324910004',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 001',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX00.2',
    snomedCode: '368646013',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 002',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX00.3',
    snomedCode: '325961725',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 003',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX00.4',
    snomedCode: '334981129',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 004',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX00.5',
    snomedCode: '310804422',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 005',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX00.6',
    snomedCode: '357720976',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 006',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX00.7',
    snomedCode: '319376338',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 007',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX00.8',
    snomedCode: '353047661',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 008',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX00.9',
    snomedCode: '371808661',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 009',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX01.0',
    snomedCode: '311036627',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 010',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX01.1',
    snomedCode: '364029952',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 011',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX01.2',
    snomedCode: '373011387',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 012',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX01.3',
    snomedCode: '360636323',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 013',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX01.4',
    snomedCode: '379054325',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 014',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX01.5',
    snomedCode: '332477225',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 015',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX01.6',
    snomedCode: '374896172',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 016',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX01.7',
    snomedCode: '368613634',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 017',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX01.8',
    snomedCode: '343435506',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 018',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX01.9',
    snomedCode: '355800596',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 019',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX02.0',
    snomedCode: '354294248',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 020',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX02.1',
    snomedCode: '303044345',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 021',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX02.2',
    snomedCode: '305692172',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 022',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX02.3',
    snomedCode: '379450475',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 023',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX02.4',
    snomedCode: '313145237',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 024',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX02.5',
    snomedCode: '363645619',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 025',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX02.6',
    snomedCode: '337490243',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 026',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX02.7',
    snomedCode: '342227674',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 027',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX02.8',
    snomedCode: '303484769',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 028',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX02.9',
    snomedCode: '349602325',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 029',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX03.0',
    snomedCode: '324724465',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 030',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX03.1',
    snomedCode: '334291830',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 031',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX03.2',
    snomedCode: '302332652',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 032',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX03.3',
    snomedCode: '342667187',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 033',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX03.4',
    snomedCode: '371026259',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 034',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
  {
    icd10Code: 'XX03.5',
    snomedCode: '370741872',
    termTitle: 'External Causes of Morbidity Clinical Entity Variant 035',
    clinicalCategory: 'Epidemiology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for external causes of morbidity with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Epidemiology physician upon escalation.',
  },
];

export function getChapterXXByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_XX_CATALOG.find((entry) => entry.icd10Code === code);
}
