// ICD-10 WHO Standard Chapter IX: Diseases of the Circulatory System
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_IX_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'IX00.1',
    snomedCode: '307421344',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 001',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX00.2',
    snomedCode: '346437930',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 002',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX00.3',
    snomedCode: '318282339',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 003',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX00.4',
    snomedCode: '361398929',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 004',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX00.5',
    snomedCode: '311622629',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 005',
    clinicalCategory: 'Cardiology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX00.6',
    snomedCode: '325297704',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 006',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX00.7',
    snomedCode: '309026668',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 007',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX00.8',
    snomedCode: '313490547',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 008',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX00.9',
    snomedCode: '350815595',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 009',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX01.0',
    snomedCode: '376558663',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 010',
    clinicalCategory: 'Cardiology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX01.1',
    snomedCode: '362317841',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 011',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX01.2',
    snomedCode: '362707164',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 012',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX01.3',
    snomedCode: '373523571',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 013',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX01.4',
    snomedCode: '316406515',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 014',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX01.5',
    snomedCode: '326946549',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 015',
    clinicalCategory: 'Cardiology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX01.6',
    snomedCode: '329624316',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 016',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX01.7',
    snomedCode: '367868138',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 017',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX01.8',
    snomedCode: '339828435',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 018',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX01.9',
    snomedCode: '300390219',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 019',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX02.0',
    snomedCode: '302287226',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 020',
    clinicalCategory: 'Cardiology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX02.1',
    snomedCode: '333252179',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 021',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX02.2',
    snomedCode: '350258197',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 022',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX02.3',
    snomedCode: '364090482',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 023',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX02.4',
    snomedCode: '358653653',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 024',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX02.5',
    snomedCode: '343519973',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 025',
    clinicalCategory: 'Cardiology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX02.6',
    snomedCode: '377468748',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 026',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX02.7',
    snomedCode: '302562411',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 027',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX02.8',
    snomedCode: '328951916',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 028',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX02.9',
    snomedCode: '307047181',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 029',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX03.0',
    snomedCode: '325382911',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 030',
    clinicalCategory: 'Cardiology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX03.1',
    snomedCode: '369629051',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 031',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX03.2',
    snomedCode: '300386640',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 032',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX03.3',
    snomedCode: '332647196',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 033',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX03.4',
    snomedCode: '367579170',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 034',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX03.5',
    snomedCode: '303592746',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 035',
    clinicalCategory: 'Cardiology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX03.6',
    snomedCode: '367281833',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 036',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX03.7',
    snomedCode: '337322388',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 037',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX03.8',
    snomedCode: '313634823',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 038',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX03.9',
    snomedCode: '370605670',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 039',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX04.0',
    snomedCode: '366412967',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 040',
    clinicalCategory: 'Cardiology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX04.1',
    snomedCode: '346096745',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 041',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX04.2',
    snomedCode: '331228809',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 042',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX04.3',
    snomedCode: '361813460',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 043',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX04.4',
    snomedCode: '345954573',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 044',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX04.5',
    snomedCode: '326694024',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 045',
    clinicalCategory: 'Cardiology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX04.6',
    snomedCode: '303604419',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 046',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX04.7',
    snomedCode: '329862863',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 047',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX04.8',
    snomedCode: '313284929',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 048',
    clinicalCategory: 'Cardiology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX04.9',
    snomedCode: '309235589',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 049',
    clinicalCategory: 'Cardiology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
  {
    icd10Code: 'IX05.0',
    snomedCode: '325431744',
    termTitle: 'Diseases of the Circulatory System Clinical Entity Variant 050',
    clinicalCategory: 'Cardiology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the circulatory system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Cardiology physician upon escalation.',
  },
];

export function getChapterIXByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_IX_CATALOG.find((entry) => entry.icd10Code === code);
}
