// ICD-10 WHO Standard Chapter XV: Pregnancy, Childbirth and the Puerperium
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_XV_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'XV00.1',
    snomedCode: '316610289',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 001',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV00.2',
    snomedCode: '362410858',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 002',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV00.3',
    snomedCode: '366773389',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 003',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV00.4',
    snomedCode: '338972848',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 004',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV00.5',
    snomedCode: '338166928',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 005',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV00.6',
    snomedCode: '322395234',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 006',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV00.7',
    snomedCode: '350815401',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 007',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV00.8',
    snomedCode: '319986634',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 008',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV00.9',
    snomedCode: '327360908',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 009',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV01.0',
    snomedCode: '371093125',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 010',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV01.1',
    snomedCode: '336431590',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 011',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV01.2',
    snomedCode: '361429892',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 012',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV01.3',
    snomedCode: '317845787',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 013',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV01.4',
    snomedCode: '368170728',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 014',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV01.5',
    snomedCode: '353913879',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 015',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV01.6',
    snomedCode: '341471836',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 016',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV01.7',
    snomedCode: '377878657',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 017',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV01.8',
    snomedCode: '361492670',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 018',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV01.9',
    snomedCode: '319790247',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 019',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV02.0',
    snomedCode: '361931854',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 020',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV02.1',
    snomedCode: '336642571',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 021',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV02.2',
    snomedCode: '310112073',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 022',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV02.3',
    snomedCode: '318949735',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 023',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV02.4',
    snomedCode: '330973943',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 024',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV02.5',
    snomedCode: '312311532',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 025',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV02.6',
    snomedCode: '324657491',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 026',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV02.7',
    snomedCode: '346227676',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 027',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV02.8',
    snomedCode: '333058663',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 028',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV02.9',
    snomedCode: '321867699',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 029',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV03.0',
    snomedCode: '371976486',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 030',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV03.1',
    snomedCode: '314950611',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 031',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV03.2',
    snomedCode: '345523995',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 032',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV03.3',
    snomedCode: '305329816',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 033',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV03.4',
    snomedCode: '372136885',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 034',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV03.5',
    snomedCode: '301148589',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 035',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV03.6',
    snomedCode: '342232168',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 036',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV03.7',
    snomedCode: '304413822',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 037',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV03.8',
    snomedCode: '314531299',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 038',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV03.9',
    snomedCode: '309644809',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 039',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
  {
    icd10Code: 'XV04.0',
    snomedCode: '322413039',
    termTitle: 'Pregnancy, Childbirth and the Puerperium Clinical Entity Variant 040',
    clinicalCategory: 'Obstetrics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for pregnancy, childbirth and the puerperium with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Obstetrics physician upon escalation.',
  },
];

export function getChapterXVByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_XV_CATALOG.find((entry) => entry.icd10Code === code);
}
