// ICD-10 WHO Standard Chapter V: Mental, Behavioral and Neurodevelopmental Disorders
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_V_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'V00.1',
    snomedCode: '345372524',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 001',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V00.2',
    snomedCode: '376399963',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 002',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V00.3',
    snomedCode: '310886826',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 003',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V00.4',
    snomedCode: '308112638',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 004',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V00.5',
    snomedCode: '358768589',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 005',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V00.6',
    snomedCode: '303068951',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 006',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V00.7',
    snomedCode: '327816329',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 007',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V00.8',
    snomedCode: '370255997',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 008',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V00.9',
    snomedCode: '323414589',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 009',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V01.0',
    snomedCode: '306669625',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 010',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V01.1',
    snomedCode: '352361762',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 011',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V01.2',
    snomedCode: '308646539',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 012',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V01.3',
    snomedCode: '335863361',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 013',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V01.4',
    snomedCode: '309339448',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 014',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V01.5',
    snomedCode: '304979466',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 015',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V01.6',
    snomedCode: '320129158',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 016',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V01.7',
    snomedCode: '302407370',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 017',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V01.8',
    snomedCode: '305002227',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 018',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V01.9',
    snomedCode: '340539975',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 019',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V02.0',
    snomedCode: '347644067',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 020',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V02.1',
    snomedCode: '345249838',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 021',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V02.2',
    snomedCode: '329663356',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 022',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V02.3',
    snomedCode: '366571283',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 023',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V02.4',
    snomedCode: '371959650',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 024',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V02.5',
    snomedCode: '369936625',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 025',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V02.6',
    snomedCode: '368658277',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 026',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V02.7',
    snomedCode: '338080594',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 027',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V02.8',
    snomedCode: '379019452',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 028',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V02.9',
    snomedCode: '336959780',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 029',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V03.0',
    snomedCode: '379013288',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 030',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V03.1',
    snomedCode: '330573942',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 031',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V03.2',
    snomedCode: '346158082',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 032',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V03.3',
    snomedCode: '341230321',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 033',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V03.4',
    snomedCode: '317157509',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 034',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V03.5',
    snomedCode: '360444632',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 035',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V03.6',
    snomedCode: '351238917',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 036',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V03.7',
    snomedCode: '322481934',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 037',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V03.8',
    snomedCode: '371211411',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 038',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V03.9',
    snomedCode: '343796123',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 039',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
  {
    icd10Code: 'V04.0',
    snomedCode: '308875090',
    termTitle: 'Mental, Behavioral and Neurodevelopmental Disorders Clinical Entity Variant 040',
    clinicalCategory: 'Psychiatry',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for mental, behavioral and neurodevelopmental disorders with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Psychiatry physician upon escalation.',
  },
];

export function getChapterVByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_V_CATALOG.find((entry) => entry.icd10Code === code);
}
