// ICD-10 WHO Standard Chapter XIV: Diseases of the Genitourinary System
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_XIV_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'XIV00.1',
    snomedCode: '328011717',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 001',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV00.2',
    snomedCode: '361694745',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 002',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV00.3',
    snomedCode: '308263424',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 003',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV00.4',
    snomedCode: '357107230',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 004',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV00.5',
    snomedCode: '344404224',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 005',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV00.6',
    snomedCode: '351970921',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 006',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV00.7',
    snomedCode: '318677369',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 007',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV00.8',
    snomedCode: '323848614',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 008',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV00.9',
    snomedCode: '354704697',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 009',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV01.0',
    snomedCode: '333834217',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 010',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV01.1',
    snomedCode: '340701157',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 011',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV01.2',
    snomedCode: '353611722',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 012',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV01.3',
    snomedCode: '318545277',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 013',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV01.4',
    snomedCode: '332756196',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 014',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV01.5',
    snomedCode: '375014335',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 015',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV01.6',
    snomedCode: '335669767',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 016',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV01.7',
    snomedCode: '374187640',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 017',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV01.8',
    snomedCode: '310690398',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 018',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV01.9',
    snomedCode: '375296266',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 019',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV02.0',
    snomedCode: '325930727',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 020',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV02.1',
    snomedCode: '301910773',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 021',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV02.2',
    snomedCode: '301903073',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 022',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV02.3',
    snomedCode: '363516669',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 023',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV02.4',
    snomedCode: '318897730',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 024',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV02.5',
    snomedCode: '341517869',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 025',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV02.6',
    snomedCode: '340317825',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 026',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV02.7',
    snomedCode: '305694687',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 027',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV02.8',
    snomedCode: '308816689',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 028',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV02.9',
    snomedCode: '377273110',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 029',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV03.0',
    snomedCode: '366746886',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 030',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV03.1',
    snomedCode: '316769505',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 031',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV03.2',
    snomedCode: '334460580',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 032',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV03.3',
    snomedCode: '349195634',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 033',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV03.4',
    snomedCode: '374712191',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 034',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV03.5',
    snomedCode: '322837488',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 035',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV03.6',
    snomedCode: '329205235',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 036',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV03.7',
    snomedCode: '371361217',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 037',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV03.8',
    snomedCode: '324677851',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 038',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV03.9',
    snomedCode: '354939848',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 039',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV04.0',
    snomedCode: '305398531',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 040',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV04.1',
    snomedCode: '303046511',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 041',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV04.2',
    snomedCode: '336813788',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 042',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV04.3',
    snomedCode: '312319635',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 043',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV04.4',
    snomedCode: '363850205',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 044',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
  {
    icd10Code: 'XIV04.5',
    snomedCode: '351201790',
    termTitle: 'Diseases of the Genitourinary System Clinical Entity Variant 045',
    clinicalCategory: 'Nephrology Urology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the genitourinary system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Nephrology Urology physician upon escalation.',
  },
];

export function getChapterXIVByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_XIV_CATALOG.find((entry) => entry.icd10Code === code);
}
