// ICD-10 WHO Standard Chapter III: Diseases of Blood and Hematopoietic Organs
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_III_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'III00.1',
    snomedCode: '335018095',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 001',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III00.2',
    snomedCode: '334695746',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 002',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III00.3',
    snomedCode: '357423309',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 003',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III00.4',
    snomedCode: '354377184',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 004',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III00.5',
    snomedCode: '335895048',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 005',
    clinicalCategory: 'Hematology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III00.6',
    snomedCode: '330199813',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 006',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III00.7',
    snomedCode: '349172453',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 007',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III00.8',
    snomedCode: '311812517',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 008',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III00.9',
    snomedCode: '364760650',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 009',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III01.0',
    snomedCode: '336693250',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 010',
    clinicalCategory: 'Hematology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III01.1',
    snomedCode: '337822124',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 011',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III01.2',
    snomedCode: '328790342',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 012',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III01.3',
    snomedCode: '347780121',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 013',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III01.4',
    snomedCode: '309276593',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 014',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III01.5',
    snomedCode: '378644947',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 015',
    clinicalCategory: 'Hematology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III01.6',
    snomedCode: '338019118',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 016',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III01.7',
    snomedCode: '314922079',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 017',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III01.8',
    snomedCode: '326091383',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 018',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III01.9',
    snomedCode: '310844643',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 019',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III02.0',
    snomedCode: '310226070',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 020',
    clinicalCategory: 'Hematology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III02.1',
    snomedCode: '326492027',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 021',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III02.2',
    snomedCode: '319377587',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 022',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III02.3',
    snomedCode: '339751198',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 023',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III02.4',
    snomedCode: '313849025',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 024',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III02.5',
    snomedCode: '369577457',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 025',
    clinicalCategory: 'Hematology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III02.6',
    snomedCode: '354369401',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 026',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III02.7',
    snomedCode: '323348641',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 027',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III02.8',
    snomedCode: '326429630',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 028',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III02.9',
    snomedCode: '338055497',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 029',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III03.0',
    snomedCode: '362568297',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 030',
    clinicalCategory: 'Hematology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III03.1',
    snomedCode: '303099464',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 031',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III03.2',
    snomedCode: '317224864',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 032',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III03.3',
    snomedCode: '362460753',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 033',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III03.4',
    snomedCode: '339508788',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 034',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III03.5',
    snomedCode: '329255245',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 035',
    clinicalCategory: 'Hematology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III03.6',
    snomedCode: '337831338',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 036',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III03.7',
    snomedCode: '323703421',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 037',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III03.8',
    snomedCode: '333990945',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 038',
    clinicalCategory: 'Hematology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III03.9',
    snomedCode: '339178348',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 039',
    clinicalCategory: 'Hematology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
  {
    icd10Code: 'III04.0',
    snomedCode: '342565547',
    termTitle: 'Diseases of Blood and Hematopoietic Organs Clinical Entity Variant 040',
    clinicalCategory: 'Hematology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of blood and hematopoietic organs with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Hematology physician upon escalation.',
  },
];

export function getChapterIIIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_III_CATALOG.find((entry) => entry.icd10Code === code);
}
