// ICD-10 WHO Standard Chapter VI: Diseases of the Nervous System
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_VI_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'VI00.1',
    snomedCode: '315533828',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 001',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI00.2',
    snomedCode: '320545730',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 002',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI00.3',
    snomedCode: '363762991',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 003',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI00.4',
    snomedCode: '348889472',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 004',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI00.5',
    snomedCode: '302520039',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 005',
    clinicalCategory: 'Neurology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI00.6',
    snomedCode: '379506671',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 006',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI00.7',
    snomedCode: '351478388',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 007',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI00.8',
    snomedCode: '335901475',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 008',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI00.9',
    snomedCode: '350151622',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 009',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI01.0',
    snomedCode: '372916584',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 010',
    clinicalCategory: 'Neurology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI01.1',
    snomedCode: '328897272',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 011',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI01.2',
    snomedCode: '330688748',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 012',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI01.3',
    snomedCode: '339939715',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 013',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI01.4',
    snomedCode: '329546348',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 014',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI01.5',
    snomedCode: '357557871',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 015',
    clinicalCategory: 'Neurology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI01.6',
    snomedCode: '373845400',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 016',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI01.7',
    snomedCode: '330164787',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 017',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI01.8',
    snomedCode: '372979514',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 018',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI01.9',
    snomedCode: '339571990',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 019',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI02.0',
    snomedCode: '347025064',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 020',
    clinicalCategory: 'Neurology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI02.1',
    snomedCode: '329095776',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 021',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI02.2',
    snomedCode: '350883296',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 022',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI02.3',
    snomedCode: '346020079',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 023',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI02.4',
    snomedCode: '340335014',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 024',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI02.5',
    snomedCode: '361651307',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 025',
    clinicalCategory: 'Neurology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI02.6',
    snomedCode: '343118524',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 026',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI02.7',
    snomedCode: '371358854',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 027',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI02.8',
    snomedCode: '311864255',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 028',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI02.9',
    snomedCode: '301739245',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 029',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI03.0',
    snomedCode: '371587386',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 030',
    clinicalCategory: 'Neurology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI03.1',
    snomedCode: '358624925',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 031',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI03.2',
    snomedCode: '377689629',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 032',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI03.3',
    snomedCode: '316109394',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 033',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI03.4',
    snomedCode: '353137200',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 034',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI03.5',
    snomedCode: '311276499',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 035',
    clinicalCategory: 'Neurology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI03.6',
    snomedCode: '313988528',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 036',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI03.7',
    snomedCode: '315470237',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 037',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI03.8',
    snomedCode: '301622772',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 038',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI03.9',
    snomedCode: '329344203',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 039',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI04.0',
    snomedCode: '336179472',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 040',
    clinicalCategory: 'Neurology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI04.1',
    snomedCode: '342730912',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 041',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI04.2',
    snomedCode: '351597176',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 042',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI04.3',
    snomedCode: '356815980',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 043',
    clinicalCategory: 'Neurology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI04.4',
    snomedCode: '327736267',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 044',
    clinicalCategory: 'Neurology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
  {
    icd10Code: 'VI04.5',
    snomedCode: '350414937',
    termTitle: 'Diseases of the Nervous System Clinical Entity Variant 045',
    clinicalCategory: 'Neurology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the nervous system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neurology physician upon escalation.',
  },
];

export function getChapterVIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_VI_CATALOG.find((entry) => entry.icd10Code === code);
}
