// ICD-10 WHO Standard Chapter XVII: Congenital Malformations, Deformations and Chromosomal Abnormalities
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_XVII_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'XVII00.1',
    snomedCode: '314022571',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 001',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII00.2',
    snomedCode: '330716071',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 002',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII00.3',
    snomedCode: '324985493',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 003',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII00.4',
    snomedCode: '360394291',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 004',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII00.5',
    snomedCode: '347619203',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 005',
    clinicalCategory: 'Genetics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII00.6',
    snomedCode: '340832689',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 006',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII00.7',
    snomedCode: '350126703',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 007',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII00.8',
    snomedCode: '315314717',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 008',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII00.9',
    snomedCode: '316304137',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 009',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII01.0',
    snomedCode: '342073026',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 010',
    clinicalCategory: 'Genetics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII01.1',
    snomedCode: '357450613',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 011',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII01.2',
    snomedCode: '367122704',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 012',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII01.3',
    snomedCode: '322958812',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 013',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII01.4',
    snomedCode: '337010180',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 014',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII01.5',
    snomedCode: '371102781',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 015',
    clinicalCategory: 'Genetics',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII01.6',
    snomedCode: '332775868',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 016',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII01.7',
    snomedCode: '352160104',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 017',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII01.8',
    snomedCode: '344912759',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 018',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII01.9',
    snomedCode: '349849927',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 019',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII02.0',
    snomedCode: '337881066',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 020',
    clinicalCategory: 'Genetics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII02.1',
    snomedCode: '337824277',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 021',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII02.2',
    snomedCode: '326042774',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 022',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII02.3',
    snomedCode: '312118003',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 023',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII02.4',
    snomedCode: '318187009',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 024',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII02.5',
    snomedCode: '375930327',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 025',
    clinicalCategory: 'Genetics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII02.6',
    snomedCode: '337876791',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 026',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII02.7',
    snomedCode: '333147470',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 027',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII02.8',
    snomedCode: '350703264',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 028',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII02.9',
    snomedCode: '360026667',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 029',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII03.0',
    snomedCode: '336016354',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 030',
    clinicalCategory: 'Genetics',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII03.1',
    snomedCode: '328040937',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 031',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII03.2',
    snomedCode: '311924391',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 032',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII03.3',
    snomedCode: '358107878',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 033',
    clinicalCategory: 'Genetics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII03.4',
    snomedCode: '313844098',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 034',
    clinicalCategory: 'Genetics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
  {
    icd10Code: 'XVII03.5',
    snomedCode: '371546755',
    termTitle: 'Congenital Malformations, Deformations and Chromosomal Abnormalities Clinical Entity Variant 035',
    clinicalCategory: 'Genetics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for congenital malformations, deformations and chromosomal abnormalities with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Genetics physician upon escalation.',
  },
];

export function getChapterXVIIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_XVII_CATALOG.find((entry) => entry.icd10Code === code);
}
