// ICD-10 WHO Standard Chapter I: Infectious and Parasitic Diseases
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_I_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'I00.1',
    snomedCode: '314447230',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 001',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I00.2',
    snomedCode: '308153760',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 002',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I00.3',
    snomedCode: '375777165',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 003',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I00.4',
    snomedCode: '365850980',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 004',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I00.5',
    snomedCode: '335123559',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 005',
    clinicalCategory: 'Infectious',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I00.6',
    snomedCode: '309921940',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 006',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I00.7',
    snomedCode: '340750420',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 007',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I00.8',
    snomedCode: '329363050',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 008',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I00.9',
    snomedCode: '339189848',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 009',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I01.0',
    snomedCode: '305117537',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 010',
    clinicalCategory: 'Infectious',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I01.1',
    snomedCode: '325954117',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 011',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I01.2',
    snomedCode: '368957420',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 012',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I01.3',
    snomedCode: '364525386',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 013',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I01.4',
    snomedCode: '316815304',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 014',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I01.5',
    snomedCode: '348339145',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 015',
    clinicalCategory: 'Infectious',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I01.6',
    snomedCode: '302422777',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 016',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I01.7',
    snomedCode: '330213072',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 017',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I01.8',
    snomedCode: '373200775',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 018',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I01.9',
    snomedCode: '325289101',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 019',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I02.0',
    snomedCode: '303434803',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 020',
    clinicalCategory: 'Infectious',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I02.1',
    snomedCode: '303729999',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 021',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I02.2',
    snomedCode: '311948882',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 022',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I02.3',
    snomedCode: '353939620',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 023',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I02.4',
    snomedCode: '313146171',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 024',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I02.5',
    snomedCode: '307948961',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 025',
    clinicalCategory: 'Infectious',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I02.6',
    snomedCode: '309352947',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 026',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I02.7',
    snomedCode: '310916566',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 027',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I02.8',
    snomedCode: '322780412',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 028',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I02.9',
    snomedCode: '326288750',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 029',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I03.0',
    snomedCode: '319619676',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 030',
    clinicalCategory: 'Infectious',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I03.1',
    snomedCode: '375446871',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 031',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I03.2',
    snomedCode: '315970465',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 032',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I03.3',
    snomedCode: '361287591',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 033',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I03.4',
    snomedCode: '327424482',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 034',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I03.5',
    snomedCode: '340289075',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 035',
    clinicalCategory: 'Infectious',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I03.6',
    snomedCode: '360552549',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 036',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I03.7',
    snomedCode: '342310677',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 037',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I03.8',
    snomedCode: '300695779',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 038',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I03.9',
    snomedCode: '317125346',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 039',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I04.0',
    snomedCode: '356222037',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 040',
    clinicalCategory: 'Infectious',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I04.1',
    snomedCode: '326302262',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 041',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I04.2',
    snomedCode: '363869553',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 042',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I04.3',
    snomedCode: '365432534',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 043',
    clinicalCategory: 'Infectious',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I04.4',
    snomedCode: '358936385',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 044',
    clinicalCategory: 'Infectious',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
  {
    icd10Code: 'I04.5',
    snomedCode: '353469375',
    termTitle: 'Infectious and Parasitic Diseases Clinical Entity Variant 045',
    clinicalCategory: 'Infectious',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for infectious and parasitic diseases with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Infectious physician upon escalation.',
  },
];

export function getChapterIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_I_CATALOG.find((entry) => entry.icd10Code === code);
}
