// ICD-10 WHO Standard Chapter VIII: Diseases of the Ear and Mastoid Process
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_VIII_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'VIII00.1',
    snomedCode: '358936401',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 001',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII00.2',
    snomedCode: '355599182',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 002',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII00.3',
    snomedCode: '302502012',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 003',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII00.4',
    snomedCode: '319126924',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 004',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII00.5',
    snomedCode: '338457403',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 005',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII00.6',
    snomedCode: '303570315',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 006',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII00.7',
    snomedCode: '314426502',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 007',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII00.8',
    snomedCode: '334167346',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 008',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII00.9',
    snomedCode: '351228200',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 009',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII01.0',
    snomedCode: '346697837',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 010',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII01.1',
    snomedCode: '316826308',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 011',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII01.2',
    snomedCode: '311227427',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 012',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII01.3',
    snomedCode: '368954554',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 013',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII01.4',
    snomedCode: '304058758',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 014',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII01.5',
    snomedCode: '324517145',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 015',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII01.6',
    snomedCode: '354627140',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 016',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII01.7',
    snomedCode: '329973828',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 017',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII01.8',
    snomedCode: '360818566',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 018',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII01.9',
    snomedCode: '377398390',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 019',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII02.0',
    snomedCode: '322836269',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 020',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII02.1',
    snomedCode: '336086488',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 021',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII02.2',
    snomedCode: '330826040',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 022',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII02.3',
    snomedCode: '320533813',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 023',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII02.4',
    snomedCode: '350615253',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 024',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII02.5',
    snomedCode: '327776971',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 025',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII02.6',
    snomedCode: '342010637',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 026',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII02.7',
    snomedCode: '377030646',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 027',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII02.8',
    snomedCode: '369320495',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 028',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII02.9',
    snomedCode: '377089006',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 029',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII03.0',
    snomedCode: '358881894',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 030',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII03.1',
    snomedCode: '315315066',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 031',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII03.2',
    snomedCode: '325858643',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 032',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII03.3',
    snomedCode: '372179539',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 033',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII03.4',
    snomedCode: '378962132',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 034',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
  {
    icd10Code: 'VIII03.5',
    snomedCode: '372984689',
    termTitle: 'Diseases of the Ear and Mastoid Process Clinical Entity Variant 035',
    clinicalCategory: 'Otolaryngology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the ear and mastoid process with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Otolaryngology physician upon escalation.',
  },
];

export function getChapterVIIIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_VIII_CATALOG.find((entry) => entry.icd10Code === code);
}
