// ICD-10 WHO Standard Chapter XII: Diseases of the Skin and Subcutaneous Tissue
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_XII_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'XII00.1',
    snomedCode: '310825592',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 001',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII00.2',
    snomedCode: '365209955',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 002',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII00.3',
    snomedCode: '360394833',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 003',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII00.4',
    snomedCode: '329105481',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 004',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII00.5',
    snomedCode: '314580073',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 005',
    clinicalCategory: 'Dermatology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII00.6',
    snomedCode: '303402573',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 006',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII00.7',
    snomedCode: '330979825',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 007',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII00.8',
    snomedCode: '360073963',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 008',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII00.9',
    snomedCode: '359331959',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 009',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII01.0',
    snomedCode: '329659026',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 010',
    clinicalCategory: 'Dermatology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII01.1',
    snomedCode: '327937210',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 011',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII01.2',
    snomedCode: '333208290',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 012',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII01.3',
    snomedCode: '357357743',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 013',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII01.4',
    snomedCode: '363972184',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 014',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII01.5',
    snomedCode: '378942883',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 015',
    clinicalCategory: 'Dermatology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII01.6',
    snomedCode: '349121780',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 016',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII01.7',
    snomedCode: '340329921',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 017',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII01.8',
    snomedCode: '375784564',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 018',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII01.9',
    snomedCode: '346363562',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 019',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII02.0',
    snomedCode: '348297911',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 020',
    clinicalCategory: 'Dermatology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII02.1',
    snomedCode: '339198001',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 021',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII02.2',
    snomedCode: '336965404',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 022',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII02.3',
    snomedCode: '337338334',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 023',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII02.4',
    snomedCode: '304638400',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 024',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII02.5',
    snomedCode: '379575071',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 025',
    clinicalCategory: 'Dermatology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII02.6',
    snomedCode: '318700712',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 026',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII02.7',
    snomedCode: '311566679',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 027',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII02.8',
    snomedCode: '342461285',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 028',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII02.9',
    snomedCode: '358986898',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 029',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII03.0',
    snomedCode: '300368620',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 030',
    clinicalCategory: 'Dermatology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII03.1',
    snomedCode: '304142297',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 031',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII03.2',
    snomedCode: '367998426',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 032',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII03.3',
    snomedCode: '357691579',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 033',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII03.4',
    snomedCode: '358914767',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 034',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII03.5',
    snomedCode: '333738317',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 035',
    clinicalCategory: 'Dermatology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII03.6',
    snomedCode: '360912302',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 036',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII03.7',
    snomedCode: '311927781',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 037',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII03.8',
    snomedCode: '303263943',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 038',
    clinicalCategory: 'Dermatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII03.9',
    snomedCode: '341115838',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 039',
    clinicalCategory: 'Dermatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
  {
    icd10Code: 'XII04.0',
    snomedCode: '329753882',
    termTitle: 'Diseases of the Skin and Subcutaneous Tissue Clinical Entity Variant 040',
    clinicalCategory: 'Dermatology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the skin and subcutaneous tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Dermatology physician upon escalation.',
  },
];

export function getChapterXIIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_XII_CATALOG.find((entry) => entry.icd10Code === code);
}
