// ICD-10 WHO Standard Chapter XXI: Factors Influencing Health Status and Contact with Health Services
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_XXI_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'XXI00.1',
    snomedCode: '363275809',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 001',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI00.2',
    snomedCode: '308058165',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 002',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI00.3',
    snomedCode: '312071861',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 003',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI00.4',
    snomedCode: '333634155',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 004',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI00.5',
    snomedCode: '307365121',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 005',
    clinicalCategory: 'Preventive',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI00.6',
    snomedCode: '307214038',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 006',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI00.7',
    snomedCode: '315409301',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 007',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI00.8',
    snomedCode: '364355088',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 008',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI00.9',
    snomedCode: '378920392',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 009',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI01.0',
    snomedCode: '300203197',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 010',
    clinicalCategory: 'Preventive',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI01.1',
    snomedCode: '328234352',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 011',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI01.2',
    snomedCode: '323866448',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 012',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI01.3',
    snomedCode: '334224432',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 013',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI01.4',
    snomedCode: '357353527',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 014',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI01.5',
    snomedCode: '304053830',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 015',
    clinicalCategory: 'Preventive',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI01.6',
    snomedCode: '377023790',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 016',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI01.7',
    snomedCode: '307198905',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 017',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI01.8',
    snomedCode: '362358651',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 018',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI01.9',
    snomedCode: '352463363',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 019',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI02.0',
    snomedCode: '369565051',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 020',
    clinicalCategory: 'Preventive',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI02.1',
    snomedCode: '349989011',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 021',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI02.2',
    snomedCode: '357184934',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 022',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI02.3',
    snomedCode: '315637619',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 023',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI02.4',
    snomedCode: '322318553',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 024',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI02.5',
    snomedCode: '302253345',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 025',
    clinicalCategory: 'Preventive',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI02.6',
    snomedCode: '314348695',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 026',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI02.7',
    snomedCode: '354801108',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 027',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI02.8',
    snomedCode: '372490632',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 028',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI02.9',
    snomedCode: '378106189',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 029',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI03.0',
    snomedCode: '316233668',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 030',
    clinicalCategory: 'Preventive',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI03.1',
    snomedCode: '302009250',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 031',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI03.2',
    snomedCode: '330550008',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 032',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI03.3',
    snomedCode: '341783250',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 033',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI03.4',
    snomedCode: '330597326',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 034',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI03.5',
    snomedCode: '321485298',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 035',
    clinicalCategory: 'Preventive',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI03.6',
    snomedCode: '321001299',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 036',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI03.7',
    snomedCode: '373116603',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 037',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI03.8',
    snomedCode: '357479091',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 038',
    clinicalCategory: 'Preventive',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI03.9',
    snomedCode: '372197975',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 039',
    clinicalCategory: 'Preventive',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
  {
    icd10Code: 'XXI04.0',
    snomedCode: '316519945',
    termTitle: 'Factors Influencing Health Status and Contact with Health Services Clinical Entity Variant 040',
    clinicalCategory: 'Preventive',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for factors influencing health status and contact with health services with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Preventive physician upon escalation.',
  },
];

export function getChapterXXIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_XXI_CATALOG.find((entry) => entry.icd10Code === code);
}
