// ICD-10 WHO Standard Chapter XVIII: Symptoms, Signs and Abnormal Clinical Findings
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_XVIII_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'XVIII00.1',
    snomedCode: '332862069',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 001',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII00.2',
    snomedCode: '340916093',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 002',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII00.3',
    snomedCode: '304024001',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 003',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII00.4',
    snomedCode: '368028042',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 004',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII00.5',
    snomedCode: '352835154',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 005',
    clinicalCategory: 'General Signs',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII00.6',
    snomedCode: '346445883',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 006',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII00.7',
    snomedCode: '359240810',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 007',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII00.8',
    snomedCode: '355877763',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 008',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII00.9',
    snomedCode: '367013501',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 009',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII01.0',
    snomedCode: '329083285',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 010',
    clinicalCategory: 'General Signs',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII01.1',
    snomedCode: '313869183',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 011',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII01.2',
    snomedCode: '351596364',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 012',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII01.3',
    snomedCode: '357780138',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 013',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII01.4',
    snomedCode: '345423765',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 014',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII01.5',
    snomedCode: '325293585',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 015',
    clinicalCategory: 'General Signs',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII01.6',
    snomedCode: '339639841',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 016',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII01.7',
    snomedCode: '301324394',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 017',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII01.8',
    snomedCode: '362744585',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 018',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII01.9',
    snomedCode: '334467445',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 019',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII02.0',
    snomedCode: '366540999',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 020',
    clinicalCategory: 'General Signs',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII02.1',
    snomedCode: '306413420',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 021',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII02.2',
    snomedCode: '324207576',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 022',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII02.3',
    snomedCode: '318642440',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 023',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII02.4',
    snomedCode: '341497767',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 024',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII02.5',
    snomedCode: '376279508',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 025',
    clinicalCategory: 'General Signs',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII02.6',
    snomedCode: '335763040',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 026',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII02.7',
    snomedCode: '335945680',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 027',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII02.8',
    snomedCode: '344589825',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 028',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII02.9',
    snomedCode: '365943420',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 029',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII03.0',
    snomedCode: '312597134',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 030',
    clinicalCategory: 'General Signs',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII03.1',
    snomedCode: '307777995',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 031',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII03.2',
    snomedCode: '314937519',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 032',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII03.3',
    snomedCode: '360474311',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 033',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII03.4',
    snomedCode: '307168220',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 034',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII03.5',
    snomedCode: '333265506',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 035',
    clinicalCategory: 'General Signs',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII03.6',
    snomedCode: '376348473',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 036',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII03.7',
    snomedCode: '367503975',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 037',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII03.8',
    snomedCode: '331928351',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 038',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII03.9',
    snomedCode: '358954416',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 039',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII04.0',
    snomedCode: '369823152',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 040',
    clinicalCategory: 'General Signs',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII04.1',
    snomedCode: '340747594',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 041',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII04.2',
    snomedCode: '362052520',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 042',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII04.3',
    snomedCode: '362802648',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 043',
    clinicalCategory: 'General Signs',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII04.4',
    snomedCode: '307217922',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 044',
    clinicalCategory: 'General Signs',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
  {
    icd10Code: 'XVIII04.5',
    snomedCode: '317004293',
    termTitle: 'Symptoms, Signs and Abnormal Clinical Findings Clinical Entity Variant 045',
    clinicalCategory: 'General Signs',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for symptoms, signs and abnormal clinical findings with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified General Signs physician upon escalation.',
  },
];

export function getChapterXVIIIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_XVIII_CATALOG.find((entry) => entry.icd10Code === code);
}
