// ICD-10 WHO Standard Chapter XIII: Diseases of the Musculoskeletal System and Connective Tissue
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_XIII_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'XIII00.1',
    snomedCode: '342140946',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 001',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII00.2',
    snomedCode: '368204425',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 002',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII00.3',
    snomedCode: '340338459',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 003',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII00.4',
    snomedCode: '361560936',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 004',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII00.5',
    snomedCode: '358957604',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 005',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII00.6',
    snomedCode: '332510415',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 006',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII00.7',
    snomedCode: '373139367',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 007',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII00.8',
    snomedCode: '366274460',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 008',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII00.9',
    snomedCode: '320834711',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 009',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII01.0',
    snomedCode: '304030273',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 010',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII01.1',
    snomedCode: '371550517',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 011',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII01.2',
    snomedCode: '379797020',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 012',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII01.3',
    snomedCode: '355715267',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 013',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII01.4',
    snomedCode: '369628619',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 014',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII01.5',
    snomedCode: '353595154',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 015',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII01.6',
    snomedCode: '338000579',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 016',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII01.7',
    snomedCode: '317032791',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 017',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII01.8',
    snomedCode: '376851180',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 018',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII01.9',
    snomedCode: '336926689',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 019',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII02.0',
    snomedCode: '331719096',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 020',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII02.1',
    snomedCode: '323278528',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 021',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII02.2',
    snomedCode: '373184721',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 022',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII02.3',
    snomedCode: '319332396',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 023',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII02.4',
    snomedCode: '314039702',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 024',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII02.5',
    snomedCode: '369459187',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 025',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII02.6',
    snomedCode: '312455047',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 026',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII02.7',
    snomedCode: '362091147',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 027',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII02.8',
    snomedCode: '369348154',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 028',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII02.9',
    snomedCode: '317425671',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 029',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII03.0',
    snomedCode: '327690088',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 030',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII03.1',
    snomedCode: '336574320',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 031',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII03.2',
    snomedCode: '361834421',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 032',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII03.3',
    snomedCode: '300470569',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 033',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII03.4',
    snomedCode: '300351935',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 034',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII03.5',
    snomedCode: '308619158',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 035',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII03.6',
    snomedCode: '366950987',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 036',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII03.7',
    snomedCode: '319952258',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 037',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII03.8',
    snomedCode: '357908396',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 038',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII03.9',
    snomedCode: '316870339',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 039',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII04.0',
    snomedCode: '379886609',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 040',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII04.1',
    snomedCode: '320562951',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 041',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII04.2',
    snomedCode: '336455532',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 042',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII04.3',
    snomedCode: '351592647',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 043',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII04.4',
    snomedCode: '369247969',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 044',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
  {
    icd10Code: 'XIII04.5',
    snomedCode: '353267071',
    termTitle: 'Diseases of the Musculoskeletal System and Connective Tissue Clinical Entity Variant 045',
    clinicalCategory: 'Orthopedics',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the musculoskeletal system and connective tissue with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Orthopedics physician upon escalation.',
  },
];

export function getChapterXIIIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_XIII_CATALOG.find((entry) => entry.icd10Code === code);
}
