// ICD-10 WHO Standard Chapter II: Neoplasms (Oncology)
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_II_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'II00.1',
    snomedCode: '371020719',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 001',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II00.2',
    snomedCode: '373638236',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 002',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II00.3',
    snomedCode: '363899135',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 003',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II00.4',
    snomedCode: '357369310',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 004',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II00.5',
    snomedCode: '311448662',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 005',
    clinicalCategory: 'Oncology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II00.6',
    snomedCode: '377470016',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 006',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II00.7',
    snomedCode: '359489982',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 007',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II00.8',
    snomedCode: '364893336',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 008',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II00.9',
    snomedCode: '336335005',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 009',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II01.0',
    snomedCode: '309136977',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 010',
    clinicalCategory: 'Oncology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II01.1',
    snomedCode: '365557735',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 011',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II01.2',
    snomedCode: '315836255',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 012',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II01.3',
    snomedCode: '307054398',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 013',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II01.4',
    snomedCode: '310408834',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 014',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II01.5',
    snomedCode: '349579827',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 015',
    clinicalCategory: 'Oncology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II01.6',
    snomedCode: '329168575',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 016',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II01.7',
    snomedCode: '323183406',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 017',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II01.8',
    snomedCode: '305584640',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 018',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II01.9',
    snomedCode: '313321096',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 019',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II02.0',
    snomedCode: '314105129',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 020',
    clinicalCategory: 'Oncology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II02.1',
    snomedCode: '379192181',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 021',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II02.2',
    snomedCode: '348555404',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 022',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II02.3',
    snomedCode: '368107329',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 023',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II02.4',
    snomedCode: '303812544',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 024',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II02.5',
    snomedCode: '374955605',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 025',
    clinicalCategory: 'Oncology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II02.6',
    snomedCode: '355285933',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 026',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II02.7',
    snomedCode: '331056285',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 027',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II02.8',
    snomedCode: '354694077',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 028',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II02.9',
    snomedCode: '379223518',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 029',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II03.0',
    snomedCode: '374680117',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 030',
    clinicalCategory: 'Oncology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II03.1',
    snomedCode: '365507998',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 031',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II03.2',
    snomedCode: '352802649',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 032',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II03.3',
    snomedCode: '358579300',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 033',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II03.4',
    snomedCode: '318532938',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 034',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II03.5',
    snomedCode: '353181455',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 035',
    clinicalCategory: 'Oncology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II03.6',
    snomedCode: '311472115',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 036',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II03.7',
    snomedCode: '368818998',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 037',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II03.8',
    snomedCode: '307952246',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 038',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II03.9',
    snomedCode: '320740562',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 039',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II04.0',
    snomedCode: '344107805',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 040',
    clinicalCategory: 'Oncology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II04.1',
    snomedCode: '321862762',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 041',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II04.2',
    snomedCode: '325365528',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 042',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II04.3',
    snomedCode: '308944042',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 043',
    clinicalCategory: 'Oncology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II04.4',
    snomedCode: '374678627',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 044',
    clinicalCategory: 'Oncology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
  {
    icd10Code: 'II04.5',
    snomedCode: '354229229',
    termTitle: 'Neoplasms (Oncology) Clinical Entity Variant 045',
    clinicalCategory: 'Oncology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for neoplasms (oncology) with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Oncology physician upon escalation.',
  },
];

export function getChapterIIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_II_CATALOG.find((entry) => entry.icd10Code === code);
}
