// ICD-10 WHO Standard Chapter VII: Diseases of the Eye and Adnexa
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_VII_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'VII00.1',
    snomedCode: '334809485',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 001',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII00.2',
    snomedCode: '312411206',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 002',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII00.3',
    snomedCode: '362592441',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 003',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII00.4',
    snomedCode: '313979195',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 004',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII00.5',
    snomedCode: '332977034',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 005',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII00.6',
    snomedCode: '346431913',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 006',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII00.7',
    snomedCode: '358140695',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 007',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII00.8',
    snomedCode: '352767167',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 008',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII00.9',
    snomedCode: '329440241',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 009',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII01.0',
    snomedCode: '359943809',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 010',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII01.1',
    snomedCode: '339228088',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 011',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII01.2',
    snomedCode: '379005109',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 012',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII01.3',
    snomedCode: '361437259',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 013',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII01.4',
    snomedCode: '309168633',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 014',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII01.5',
    snomedCode: '360070898',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 015',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII01.6',
    snomedCode: '322923658',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 016',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII01.7',
    snomedCode: '304205575',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 017',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII01.8',
    snomedCode: '332002315',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 018',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII01.9',
    snomedCode: '330439882',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 019',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII02.0',
    snomedCode: '308716912',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 020',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII02.1',
    snomedCode: '372503528',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 021',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII02.2',
    snomedCode: '347129001',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 022',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII02.3',
    snomedCode: '308156276',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 023',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII02.4',
    snomedCode: '359321633',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 024',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII02.5',
    snomedCode: '375208385',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 025',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII02.6',
    snomedCode: '363205408',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 026',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII02.7',
    snomedCode: '358045054',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 027',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII02.8',
    snomedCode: '363515150',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 028',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII02.9',
    snomedCode: '304655024',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 029',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII03.0',
    snomedCode: '352881080',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 030',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII03.1',
    snomedCode: '377924418',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 031',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII03.2',
    snomedCode: '364160333',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 032',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII03.3',
    snomedCode: '327368943',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 033',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII03.4',
    snomedCode: '342052965',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 034',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII03.5',
    snomedCode: '339911993',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 035',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII03.6',
    snomedCode: '353252462',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 036',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII03.7',
    snomedCode: '330289930',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 037',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII03.8',
    snomedCode: '346346267',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 038',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII03.9',
    snomedCode: '332859388',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 039',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
  {
    icd10Code: 'VII04.0',
    snomedCode: '366996552',
    termTitle: 'Diseases of the Eye and Adnexa Clinical Entity Variant 040',
    clinicalCategory: 'Ophthalmology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the eye and adnexa with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Ophthalmology physician upon escalation.',
  },
];

export function getChapterVIIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_VII_CATALOG.find((entry) => entry.icd10Code === code);
}
