// ICD-10 WHO Standard Chapter XVI: Certain Conditions Originating in the Perinatal Period
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_XVI_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'XVI00.1',
    snomedCode: '364123791',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 001',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI00.2',
    snomedCode: '368028002',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 002',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI00.3',
    snomedCode: '308244567',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 003',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI00.4',
    snomedCode: '353157638',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 004',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI00.5',
    snomedCode: '309156051',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 005',
    clinicalCategory: 'Neonatology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI00.6',
    snomedCode: '376377505',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 006',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI00.7',
    snomedCode: '302041697',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 007',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI00.8',
    snomedCode: '357920782',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 008',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI00.9',
    snomedCode: '362079931',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 009',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI01.0',
    snomedCode: '361379300',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 010',
    clinicalCategory: 'Neonatology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI01.1',
    snomedCode: '362299942',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 011',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI01.2',
    snomedCode: '339299768',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 012',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI01.3',
    snomedCode: '324229691',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 013',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI01.4',
    snomedCode: '316595018',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 014',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI01.5',
    snomedCode: '371462276',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 015',
    clinicalCategory: 'Neonatology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI01.6',
    snomedCode: '367525861',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 016',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI01.7',
    snomedCode: '346348322',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 017',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI01.8',
    snomedCode: '369225619',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 018',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI01.9',
    snomedCode: '335299943',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 019',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI02.0',
    snomedCode: '336231345',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 020',
    clinicalCategory: 'Neonatology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI02.1',
    snomedCode: '319020581',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 021',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI02.2',
    snomedCode: '316004048',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 022',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI02.3',
    snomedCode: '321110307',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 023',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI02.4',
    snomedCode: '370710523',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 024',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI02.5',
    snomedCode: '366507518',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 025',
    clinicalCategory: 'Neonatology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI02.6',
    snomedCode: '363482293',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 026',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI02.7',
    snomedCode: '376580038',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 027',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI02.8',
    snomedCode: '351335530',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 028',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI02.9',
    snomedCode: '347968360',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 029',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI03.0',
    snomedCode: '322108216',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 030',
    clinicalCategory: 'Neonatology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI03.1',
    snomedCode: '354900255',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 031',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI03.2',
    snomedCode: '336166727',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 032',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI03.3',
    snomedCode: '310877231',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 033',
    clinicalCategory: 'Neonatology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI03.4',
    snomedCode: '338493061',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 034',
    clinicalCategory: 'Neonatology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
  {
    icd10Code: 'XVI03.5',
    snomedCode: '368830042',
    termTitle: 'Certain Conditions Originating in the Perinatal Period Clinical Entity Variant 035',
    clinicalCategory: 'Neonatology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for certain conditions originating in the perinatal period with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Neonatology physician upon escalation.',
  },
];

export function getChapterXVIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_XVI_CATALOG.find((entry) => entry.icd10Code === code);
}
