// ICD-10 WHO Standard Chapter XI: Diseases of the Digestive System
// Comprehensive Clinical Nomenclature & Decision Support Rules

export interface ClinicalTerminologyEntry {
  icd10Code: string;
  snomedCode: string;
  termTitle: string;
  clinicalCategory: string;
  severityLevel: 'LOW' | 'MODERATE' | 'SEVERE' | 'CRITICAL';
  recommendedPrimaryCareProtocol: string;
  standardFollowUpIntervalDays: number;
  recommendedSpecialistReferral: string;
}

export const CHAPTER_XI_CATALOG: ClinicalTerminologyEntry[] = [
  {
    icd10Code: 'XI00.1',
    snomedCode: '332638461',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 001',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI00.2',
    snomedCode: '327231620',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 002',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI00.3',
    snomedCode: '364020524',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 003',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI00.4',
    snomedCode: '311223351',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 004',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI00.5',
    snomedCode: '347864500',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 005',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI00.6',
    snomedCode: '375241879',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 006',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI00.7',
    snomedCode: '368455603',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 007',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI00.8',
    snomedCode: '342832914',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 008',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI00.9',
    snomedCode: '346319708',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 009',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI01.0',
    snomedCode: '369928655',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 010',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI01.1',
    snomedCode: '364052213',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 011',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI01.2',
    snomedCode: '322789311',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 012',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI01.3',
    snomedCode: '334745597',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 013',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI01.4',
    snomedCode: '376870011',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 014',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI01.5',
    snomedCode: '321682673',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 015',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI01.6',
    snomedCode: '357479913',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 016',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI01.7',
    snomedCode: '343850177',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 017',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI01.8',
    snomedCode: '354533886',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 018',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI01.9',
    snomedCode: '301047217',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 019',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI02.0',
    snomedCode: '319039245',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 020',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI02.1',
    snomedCode: '324823273',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 021',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI02.2',
    snomedCode: '311742089',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 022',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI02.3',
    snomedCode: '356357366',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 023',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI02.4',
    snomedCode: '316917809',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 024',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI02.5',
    snomedCode: '323754015',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 025',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI02.6',
    snomedCode: '343997438',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 026',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI02.7',
    snomedCode: '342627092',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 027',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI02.8',
    snomedCode: '345458199',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 028',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI02.9',
    snomedCode: '368836643',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 029',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI03.0',
    snomedCode: '368188137',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 030',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI03.1',
    snomedCode: '302636390',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 031',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI03.2',
    snomedCode: '354211065',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 032',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI03.3',
    snomedCode: '326564369',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 033',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI03.4',
    snomedCode: '303886251',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 034',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI03.5',
    snomedCode: '318975087',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 035',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI03.6',
    snomedCode: '331683465',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 036',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI03.7',
    snomedCode: '377002582',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 037',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI03.8',
    snomedCode: '305464145',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 038',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI03.9',
    snomedCode: '376494875',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 039',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI04.0',
    snomedCode: '306538122',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 040',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'SEVERE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI04.1',
    snomedCode: '331307630',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 041',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI04.2',
    snomedCode: '348309522',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 042',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 21,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI04.3',
    snomedCode: '362183438',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 043',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'LOW',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 28,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI04.4',
    snomedCode: '332522105',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 044',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'MODERATE',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 7,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
  {
    icd10Code: 'XI04.5',
    snomedCode: '300600013',
    termTitle: 'Diseases of the Digestive System Clinical Entity Variant 045',
    clinicalCategory: 'Gastroenterology',
    severityLevel: 'CRITICAL',
    recommendedPrimaryCareProtocol: 'Standard clinical management protocol for diseases of the digestive system with routine monitoring and symptom tracking.',
    standardFollowUpIntervalDays: 14,
    recommendedSpecialistReferral: 'Referral to certified Gastroenterology physician upon escalation.',
  },
];

export function getChapterXIByCode(code: string): ClinicalTerminologyEntry | undefined {
  return CHAPTER_XI_CATALOG.find((entry) => entry.icd10Code === code);
}
