// SNOMED-CT (Systematized Nomenclature of Medicine -- Clinical Terms) Concept Matrix
// Standard Clinical Finding & Disorder Ontology

export interface SNOMEDConcept {
  conceptId: string;
  fullySpecifiedName: string;
  preferredTerm: string;
  conceptClass: 'Finding' | 'Disorder' | 'Procedure' | 'Morphologic Abnormality';
  clinicalDomain: string;
  anatomicalSite: string;
  icd10MappingHint: string;
  clinicalDefinition: string;
}

export const SNOMED_CT_CONCEPTS: SNOMEDConcept[] = [
  {
    conceptId: '400000017',
    fullySpecifiedName: 'Cardiovascular Finding entity 01 (finding)',
    preferredTerm: 'Cardiovascular Finding 01',
    conceptClass: 'Finding',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.1',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000034',
    fullySpecifiedName: 'Cardiovascular Finding entity 02 (finding)',
    preferredTerm: 'Cardiovascular Finding 02',
    conceptClass: 'Disorder',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.2',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000051',
    fullySpecifiedName: 'Cardiovascular Finding entity 03 (finding)',
    preferredTerm: 'Cardiovascular Finding 03',
    conceptClass: 'Finding',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.3',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000068',
    fullySpecifiedName: 'Cardiovascular Finding entity 04 (finding)',
    preferredTerm: 'Cardiovascular Finding 04',
    conceptClass: 'Disorder',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.4',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000085',
    fullySpecifiedName: 'Cardiovascular Finding entity 05 (finding)',
    preferredTerm: 'Cardiovascular Finding 05',
    conceptClass: 'Finding',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.5',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000102',
    fullySpecifiedName: 'Cardiovascular Finding entity 06 (finding)',
    preferredTerm: 'Cardiovascular Finding 06',
    conceptClass: 'Disorder',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.6',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000119',
    fullySpecifiedName: 'Cardiovascular Finding entity 07 (finding)',
    preferredTerm: 'Cardiovascular Finding 07',
    conceptClass: 'Finding',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.7',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000136',
    fullySpecifiedName: 'Cardiovascular Finding entity 08 (finding)',
    preferredTerm: 'Cardiovascular Finding 08',
    conceptClass: 'Disorder',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.8',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000153',
    fullySpecifiedName: 'Cardiovascular Finding entity 09 (finding)',
    preferredTerm: 'Cardiovascular Finding 09',
    conceptClass: 'Finding',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.9',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000170',
    fullySpecifiedName: 'Cardiovascular Finding entity 10 (finding)',
    preferredTerm: 'Cardiovascular Finding 10',
    conceptClass: 'Disorder',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.0',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000187',
    fullySpecifiedName: 'Cardiovascular Finding entity 11 (finding)',
    preferredTerm: 'Cardiovascular Finding 11',
    conceptClass: 'Finding',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.1',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000204',
    fullySpecifiedName: 'Cardiovascular Finding entity 12 (finding)',
    preferredTerm: 'Cardiovascular Finding 12',
    conceptClass: 'Disorder',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.2',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000221',
    fullySpecifiedName: 'Cardiovascular Finding entity 13 (finding)',
    preferredTerm: 'Cardiovascular Finding 13',
    conceptClass: 'Finding',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.3',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000238',
    fullySpecifiedName: 'Cardiovascular Finding entity 14 (finding)',
    preferredTerm: 'Cardiovascular Finding 14',
    conceptClass: 'Disorder',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.4',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000255',
    fullySpecifiedName: 'Cardiovascular Finding entity 15 (finding)',
    preferredTerm: 'Cardiovascular Finding 15',
    conceptClass: 'Finding',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.5',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000272',
    fullySpecifiedName: 'Cardiovascular Finding entity 16 (finding)',
    preferredTerm: 'Cardiovascular Finding 16',
    conceptClass: 'Disorder',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.6',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000289',
    fullySpecifiedName: 'Cardiovascular Finding entity 17 (finding)',
    preferredTerm: 'Cardiovascular Finding 17',
    conceptClass: 'Finding',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.7',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000306',
    fullySpecifiedName: 'Cardiovascular Finding entity 18 (finding)',
    preferredTerm: 'Cardiovascular Finding 18',
    conceptClass: 'Disorder',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.8',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000323',
    fullySpecifiedName: 'Cardiovascular Finding entity 19 (finding)',
    preferredTerm: 'Cardiovascular Finding 19',
    conceptClass: 'Finding',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.9',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000340',
    fullySpecifiedName: 'Cardiovascular Finding entity 20 (finding)',
    preferredTerm: 'Cardiovascular Finding 20',
    conceptClass: 'Disorder',
    clinicalDomain: 'Cardiovascular Finding',
    anatomicalSite: 'Heart & Great Vessels',
    icd10MappingHint: 'CAR.0',
    clinicalDefinition: 'Standardized clinical finding representing cardiovascular finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000357',
    fullySpecifiedName: 'Neurological Finding entity 01 (finding)',
    preferredTerm: 'Neurological Finding 01',
    conceptClass: 'Finding',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.1',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000374',
    fullySpecifiedName: 'Neurological Finding entity 02 (finding)',
    preferredTerm: 'Neurological Finding 02',
    conceptClass: 'Disorder',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.2',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000391',
    fullySpecifiedName: 'Neurological Finding entity 03 (finding)',
    preferredTerm: 'Neurological Finding 03',
    conceptClass: 'Finding',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.3',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000408',
    fullySpecifiedName: 'Neurological Finding entity 04 (finding)',
    preferredTerm: 'Neurological Finding 04',
    conceptClass: 'Disorder',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.4',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000425',
    fullySpecifiedName: 'Neurological Finding entity 05 (finding)',
    preferredTerm: 'Neurological Finding 05',
    conceptClass: 'Finding',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.5',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000442',
    fullySpecifiedName: 'Neurological Finding entity 06 (finding)',
    preferredTerm: 'Neurological Finding 06',
    conceptClass: 'Disorder',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.6',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000459',
    fullySpecifiedName: 'Neurological Finding entity 07 (finding)',
    preferredTerm: 'Neurological Finding 07',
    conceptClass: 'Finding',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.7',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000476',
    fullySpecifiedName: 'Neurological Finding entity 08 (finding)',
    preferredTerm: 'Neurological Finding 08',
    conceptClass: 'Disorder',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.8',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000493',
    fullySpecifiedName: 'Neurological Finding entity 09 (finding)',
    preferredTerm: 'Neurological Finding 09',
    conceptClass: 'Finding',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.9',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000510',
    fullySpecifiedName: 'Neurological Finding entity 10 (finding)',
    preferredTerm: 'Neurological Finding 10',
    conceptClass: 'Disorder',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.0',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000527',
    fullySpecifiedName: 'Neurological Finding entity 11 (finding)',
    preferredTerm: 'Neurological Finding 11',
    conceptClass: 'Finding',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.1',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000544',
    fullySpecifiedName: 'Neurological Finding entity 12 (finding)',
    preferredTerm: 'Neurological Finding 12',
    conceptClass: 'Disorder',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.2',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000561',
    fullySpecifiedName: 'Neurological Finding entity 13 (finding)',
    preferredTerm: 'Neurological Finding 13',
    conceptClass: 'Finding',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.3',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000578',
    fullySpecifiedName: 'Neurological Finding entity 14 (finding)',
    preferredTerm: 'Neurological Finding 14',
    conceptClass: 'Disorder',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.4',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000595',
    fullySpecifiedName: 'Neurological Finding entity 15 (finding)',
    preferredTerm: 'Neurological Finding 15',
    conceptClass: 'Finding',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.5',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000612',
    fullySpecifiedName: 'Neurological Finding entity 16 (finding)',
    preferredTerm: 'Neurological Finding 16',
    conceptClass: 'Disorder',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.6',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000629',
    fullySpecifiedName: 'Neurological Finding entity 17 (finding)',
    preferredTerm: 'Neurological Finding 17',
    conceptClass: 'Finding',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.7',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000646',
    fullySpecifiedName: 'Neurological Finding entity 18 (finding)',
    preferredTerm: 'Neurological Finding 18',
    conceptClass: 'Disorder',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.8',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000663',
    fullySpecifiedName: 'Neurological Finding entity 19 (finding)',
    preferredTerm: 'Neurological Finding 19',
    conceptClass: 'Finding',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.9',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000680',
    fullySpecifiedName: 'Neurological Finding entity 20 (finding)',
    preferredTerm: 'Neurological Finding 20',
    conceptClass: 'Disorder',
    clinicalDomain: 'Neurological Finding',
    anatomicalSite: 'Central & Peripheral Nervous System',
    icd10MappingHint: 'NEU.0',
    clinicalDefinition: 'Standardized clinical finding representing neurological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000697',
    fullySpecifiedName: 'Respiratory Finding entity 01 (finding)',
    preferredTerm: 'Respiratory Finding 01',
    conceptClass: 'Finding',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.1',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000714',
    fullySpecifiedName: 'Respiratory Finding entity 02 (finding)',
    preferredTerm: 'Respiratory Finding 02',
    conceptClass: 'Disorder',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.2',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000731',
    fullySpecifiedName: 'Respiratory Finding entity 03 (finding)',
    preferredTerm: 'Respiratory Finding 03',
    conceptClass: 'Finding',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.3',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000748',
    fullySpecifiedName: 'Respiratory Finding entity 04 (finding)',
    preferredTerm: 'Respiratory Finding 04',
    conceptClass: 'Disorder',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.4',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000765',
    fullySpecifiedName: 'Respiratory Finding entity 05 (finding)',
    preferredTerm: 'Respiratory Finding 05',
    conceptClass: 'Finding',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.5',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000782',
    fullySpecifiedName: 'Respiratory Finding entity 06 (finding)',
    preferredTerm: 'Respiratory Finding 06',
    conceptClass: 'Disorder',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.6',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000799',
    fullySpecifiedName: 'Respiratory Finding entity 07 (finding)',
    preferredTerm: 'Respiratory Finding 07',
    conceptClass: 'Finding',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.7',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000816',
    fullySpecifiedName: 'Respiratory Finding entity 08 (finding)',
    preferredTerm: 'Respiratory Finding 08',
    conceptClass: 'Disorder',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.8',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000833',
    fullySpecifiedName: 'Respiratory Finding entity 09 (finding)',
    preferredTerm: 'Respiratory Finding 09',
    conceptClass: 'Finding',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.9',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000850',
    fullySpecifiedName: 'Respiratory Finding entity 10 (finding)',
    preferredTerm: 'Respiratory Finding 10',
    conceptClass: 'Disorder',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.0',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000867',
    fullySpecifiedName: 'Respiratory Finding entity 11 (finding)',
    preferredTerm: 'Respiratory Finding 11',
    conceptClass: 'Finding',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.1',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000884',
    fullySpecifiedName: 'Respiratory Finding entity 12 (finding)',
    preferredTerm: 'Respiratory Finding 12',
    conceptClass: 'Disorder',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.2',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000901',
    fullySpecifiedName: 'Respiratory Finding entity 13 (finding)',
    preferredTerm: 'Respiratory Finding 13',
    conceptClass: 'Finding',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.3',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000918',
    fullySpecifiedName: 'Respiratory Finding entity 14 (finding)',
    preferredTerm: 'Respiratory Finding 14',
    conceptClass: 'Disorder',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.4',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000935',
    fullySpecifiedName: 'Respiratory Finding entity 15 (finding)',
    preferredTerm: 'Respiratory Finding 15',
    conceptClass: 'Finding',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.5',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000952',
    fullySpecifiedName: 'Respiratory Finding entity 16 (finding)',
    preferredTerm: 'Respiratory Finding 16',
    conceptClass: 'Disorder',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.6',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000969',
    fullySpecifiedName: 'Respiratory Finding entity 17 (finding)',
    preferredTerm: 'Respiratory Finding 17',
    conceptClass: 'Finding',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.7',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400000986',
    fullySpecifiedName: 'Respiratory Finding entity 18 (finding)',
    preferredTerm: 'Respiratory Finding 18',
    conceptClass: 'Disorder',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.8',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001003',
    fullySpecifiedName: 'Respiratory Finding entity 19 (finding)',
    preferredTerm: 'Respiratory Finding 19',
    conceptClass: 'Finding',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.9',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001020',
    fullySpecifiedName: 'Respiratory Finding entity 20 (finding)',
    preferredTerm: 'Respiratory Finding 20',
    conceptClass: 'Disorder',
    clinicalDomain: 'Respiratory Finding',
    anatomicalSite: 'Lungs & Tracheobronchial Tree',
    icd10MappingHint: 'RES.0',
    clinicalDefinition: 'Standardized clinical finding representing respiratory finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001037',
    fullySpecifiedName: 'Dermatological Finding entity 01 (finding)',
    preferredTerm: 'Dermatological Finding 01',
    conceptClass: 'Finding',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.1',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001054',
    fullySpecifiedName: 'Dermatological Finding entity 02 (finding)',
    preferredTerm: 'Dermatological Finding 02',
    conceptClass: 'Disorder',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.2',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001071',
    fullySpecifiedName: 'Dermatological Finding entity 03 (finding)',
    preferredTerm: 'Dermatological Finding 03',
    conceptClass: 'Finding',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.3',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001088',
    fullySpecifiedName: 'Dermatological Finding entity 04 (finding)',
    preferredTerm: 'Dermatological Finding 04',
    conceptClass: 'Disorder',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.4',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001105',
    fullySpecifiedName: 'Dermatological Finding entity 05 (finding)',
    preferredTerm: 'Dermatological Finding 05',
    conceptClass: 'Finding',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.5',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001122',
    fullySpecifiedName: 'Dermatological Finding entity 06 (finding)',
    preferredTerm: 'Dermatological Finding 06',
    conceptClass: 'Disorder',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.6',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001139',
    fullySpecifiedName: 'Dermatological Finding entity 07 (finding)',
    preferredTerm: 'Dermatological Finding 07',
    conceptClass: 'Finding',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.7',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001156',
    fullySpecifiedName: 'Dermatological Finding entity 08 (finding)',
    preferredTerm: 'Dermatological Finding 08',
    conceptClass: 'Disorder',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.8',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001173',
    fullySpecifiedName: 'Dermatological Finding entity 09 (finding)',
    preferredTerm: 'Dermatological Finding 09',
    conceptClass: 'Finding',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.9',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001190',
    fullySpecifiedName: 'Dermatological Finding entity 10 (finding)',
    preferredTerm: 'Dermatological Finding 10',
    conceptClass: 'Disorder',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.0',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001207',
    fullySpecifiedName: 'Dermatological Finding entity 11 (finding)',
    preferredTerm: 'Dermatological Finding 11',
    conceptClass: 'Finding',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.1',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001224',
    fullySpecifiedName: 'Dermatological Finding entity 12 (finding)',
    preferredTerm: 'Dermatological Finding 12',
    conceptClass: 'Disorder',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.2',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001241',
    fullySpecifiedName: 'Dermatological Finding entity 13 (finding)',
    preferredTerm: 'Dermatological Finding 13',
    conceptClass: 'Finding',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.3',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001258',
    fullySpecifiedName: 'Dermatological Finding entity 14 (finding)',
    preferredTerm: 'Dermatological Finding 14',
    conceptClass: 'Disorder',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.4',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001275',
    fullySpecifiedName: 'Dermatological Finding entity 15 (finding)',
    preferredTerm: 'Dermatological Finding 15',
    conceptClass: 'Finding',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.5',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001292',
    fullySpecifiedName: 'Dermatological Finding entity 16 (finding)',
    preferredTerm: 'Dermatological Finding 16',
    conceptClass: 'Disorder',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.6',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001309',
    fullySpecifiedName: 'Dermatological Finding entity 17 (finding)',
    preferredTerm: 'Dermatological Finding 17',
    conceptClass: 'Finding',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.7',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001326',
    fullySpecifiedName: 'Dermatological Finding entity 18 (finding)',
    preferredTerm: 'Dermatological Finding 18',
    conceptClass: 'Disorder',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.8',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001343',
    fullySpecifiedName: 'Dermatological Finding entity 19 (finding)',
    preferredTerm: 'Dermatological Finding 19',
    conceptClass: 'Finding',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.9',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001360',
    fullySpecifiedName: 'Dermatological Finding entity 20 (finding)',
    preferredTerm: 'Dermatological Finding 20',
    conceptClass: 'Disorder',
    clinicalDomain: 'Dermatological Finding',
    anatomicalSite: 'Integumentary System',
    icd10MappingHint: 'DER.0',
    clinicalDefinition: 'Standardized clinical finding representing dermatological finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001377',
    fullySpecifiedName: 'Gastrointestinal Finding entity 01 (finding)',
    preferredTerm: 'Gastrointestinal Finding 01',
    conceptClass: 'Finding',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.1',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001394',
    fullySpecifiedName: 'Gastrointestinal Finding entity 02 (finding)',
    preferredTerm: 'Gastrointestinal Finding 02',
    conceptClass: 'Disorder',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.2',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001411',
    fullySpecifiedName: 'Gastrointestinal Finding entity 03 (finding)',
    preferredTerm: 'Gastrointestinal Finding 03',
    conceptClass: 'Finding',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.3',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001428',
    fullySpecifiedName: 'Gastrointestinal Finding entity 04 (finding)',
    preferredTerm: 'Gastrointestinal Finding 04',
    conceptClass: 'Disorder',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.4',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001445',
    fullySpecifiedName: 'Gastrointestinal Finding entity 05 (finding)',
    preferredTerm: 'Gastrointestinal Finding 05',
    conceptClass: 'Finding',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.5',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001462',
    fullySpecifiedName: 'Gastrointestinal Finding entity 06 (finding)',
    preferredTerm: 'Gastrointestinal Finding 06',
    conceptClass: 'Disorder',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.6',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001479',
    fullySpecifiedName: 'Gastrointestinal Finding entity 07 (finding)',
    preferredTerm: 'Gastrointestinal Finding 07',
    conceptClass: 'Finding',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.7',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001496',
    fullySpecifiedName: 'Gastrointestinal Finding entity 08 (finding)',
    preferredTerm: 'Gastrointestinal Finding 08',
    conceptClass: 'Disorder',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.8',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001513',
    fullySpecifiedName: 'Gastrointestinal Finding entity 09 (finding)',
    preferredTerm: 'Gastrointestinal Finding 09',
    conceptClass: 'Finding',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.9',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001530',
    fullySpecifiedName: 'Gastrointestinal Finding entity 10 (finding)',
    preferredTerm: 'Gastrointestinal Finding 10',
    conceptClass: 'Disorder',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.0',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001547',
    fullySpecifiedName: 'Gastrointestinal Finding entity 11 (finding)',
    preferredTerm: 'Gastrointestinal Finding 11',
    conceptClass: 'Finding',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.1',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001564',
    fullySpecifiedName: 'Gastrointestinal Finding entity 12 (finding)',
    preferredTerm: 'Gastrointestinal Finding 12',
    conceptClass: 'Disorder',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.2',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001581',
    fullySpecifiedName: 'Gastrointestinal Finding entity 13 (finding)',
    preferredTerm: 'Gastrointestinal Finding 13',
    conceptClass: 'Finding',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.3',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001598',
    fullySpecifiedName: 'Gastrointestinal Finding entity 14 (finding)',
    preferredTerm: 'Gastrointestinal Finding 14',
    conceptClass: 'Disorder',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.4',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001615',
    fullySpecifiedName: 'Gastrointestinal Finding entity 15 (finding)',
    preferredTerm: 'Gastrointestinal Finding 15',
    conceptClass: 'Finding',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.5',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001632',
    fullySpecifiedName: 'Gastrointestinal Finding entity 16 (finding)',
    preferredTerm: 'Gastrointestinal Finding 16',
    conceptClass: 'Disorder',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.6',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001649',
    fullySpecifiedName: 'Gastrointestinal Finding entity 17 (finding)',
    preferredTerm: 'Gastrointestinal Finding 17',
    conceptClass: 'Finding',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.7',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001666',
    fullySpecifiedName: 'Gastrointestinal Finding entity 18 (finding)',
    preferredTerm: 'Gastrointestinal Finding 18',
    conceptClass: 'Disorder',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.8',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001683',
    fullySpecifiedName: 'Gastrointestinal Finding entity 19 (finding)',
    preferredTerm: 'Gastrointestinal Finding 19',
    conceptClass: 'Finding',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.9',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001700',
    fullySpecifiedName: 'Gastrointestinal Finding entity 20 (finding)',
    preferredTerm: 'Gastrointestinal Finding 20',
    conceptClass: 'Disorder',
    clinicalDomain: 'Gastrointestinal Finding',
    anatomicalSite: 'Alimentary Tract & Hepatic',
    icd10MappingHint: 'GI.0',
    clinicalDefinition: 'Standardized clinical finding representing gastrointestinal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001717',
    fullySpecifiedName: 'Musculoskeletal Finding entity 01 (finding)',
    preferredTerm: 'Musculoskeletal Finding 01',
    conceptClass: 'Finding',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.1',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001734',
    fullySpecifiedName: 'Musculoskeletal Finding entity 02 (finding)',
    preferredTerm: 'Musculoskeletal Finding 02',
    conceptClass: 'Disorder',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.2',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001751',
    fullySpecifiedName: 'Musculoskeletal Finding entity 03 (finding)',
    preferredTerm: 'Musculoskeletal Finding 03',
    conceptClass: 'Finding',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.3',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001768',
    fullySpecifiedName: 'Musculoskeletal Finding entity 04 (finding)',
    preferredTerm: 'Musculoskeletal Finding 04',
    conceptClass: 'Disorder',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.4',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001785',
    fullySpecifiedName: 'Musculoskeletal Finding entity 05 (finding)',
    preferredTerm: 'Musculoskeletal Finding 05',
    conceptClass: 'Finding',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.5',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001802',
    fullySpecifiedName: 'Musculoskeletal Finding entity 06 (finding)',
    preferredTerm: 'Musculoskeletal Finding 06',
    conceptClass: 'Disorder',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.6',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001819',
    fullySpecifiedName: 'Musculoskeletal Finding entity 07 (finding)',
    preferredTerm: 'Musculoskeletal Finding 07',
    conceptClass: 'Finding',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.7',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001836',
    fullySpecifiedName: 'Musculoskeletal Finding entity 08 (finding)',
    preferredTerm: 'Musculoskeletal Finding 08',
    conceptClass: 'Disorder',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.8',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001853',
    fullySpecifiedName: 'Musculoskeletal Finding entity 09 (finding)',
    preferredTerm: 'Musculoskeletal Finding 09',
    conceptClass: 'Finding',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.9',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001870',
    fullySpecifiedName: 'Musculoskeletal Finding entity 10 (finding)',
    preferredTerm: 'Musculoskeletal Finding 10',
    conceptClass: 'Disorder',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.0',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001887',
    fullySpecifiedName: 'Musculoskeletal Finding entity 11 (finding)',
    preferredTerm: 'Musculoskeletal Finding 11',
    conceptClass: 'Finding',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.1',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001904',
    fullySpecifiedName: 'Musculoskeletal Finding entity 12 (finding)',
    preferredTerm: 'Musculoskeletal Finding 12',
    conceptClass: 'Disorder',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.2',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001921',
    fullySpecifiedName: 'Musculoskeletal Finding entity 13 (finding)',
    preferredTerm: 'Musculoskeletal Finding 13',
    conceptClass: 'Finding',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.3',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001938',
    fullySpecifiedName: 'Musculoskeletal Finding entity 14 (finding)',
    preferredTerm: 'Musculoskeletal Finding 14',
    conceptClass: 'Disorder',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.4',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001955',
    fullySpecifiedName: 'Musculoskeletal Finding entity 15 (finding)',
    preferredTerm: 'Musculoskeletal Finding 15',
    conceptClass: 'Finding',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.5',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001972',
    fullySpecifiedName: 'Musculoskeletal Finding entity 16 (finding)',
    preferredTerm: 'Musculoskeletal Finding 16',
    conceptClass: 'Disorder',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.6',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400001989',
    fullySpecifiedName: 'Musculoskeletal Finding entity 17 (finding)',
    preferredTerm: 'Musculoskeletal Finding 17',
    conceptClass: 'Finding',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.7',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002006',
    fullySpecifiedName: 'Musculoskeletal Finding entity 18 (finding)',
    preferredTerm: 'Musculoskeletal Finding 18',
    conceptClass: 'Disorder',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.8',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002023',
    fullySpecifiedName: 'Musculoskeletal Finding entity 19 (finding)',
    preferredTerm: 'Musculoskeletal Finding 19',
    conceptClass: 'Finding',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.9',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002040',
    fullySpecifiedName: 'Musculoskeletal Finding entity 20 (finding)',
    preferredTerm: 'Musculoskeletal Finding 20',
    conceptClass: 'Disorder',
    clinicalDomain: 'Musculoskeletal Finding',
    anatomicalSite: 'Bones, Joints & Soft Tissue',
    icd10MappingHint: 'MSK.0',
    clinicalDefinition: 'Standardized clinical finding representing musculoskeletal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002057',
    fullySpecifiedName: 'Endocrine Finding entity 01 (finding)',
    preferredTerm: 'Endocrine Finding 01',
    conceptClass: 'Finding',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.1',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002074',
    fullySpecifiedName: 'Endocrine Finding entity 02 (finding)',
    preferredTerm: 'Endocrine Finding 02',
    conceptClass: 'Disorder',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.2',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002091',
    fullySpecifiedName: 'Endocrine Finding entity 03 (finding)',
    preferredTerm: 'Endocrine Finding 03',
    conceptClass: 'Finding',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.3',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002108',
    fullySpecifiedName: 'Endocrine Finding entity 04 (finding)',
    preferredTerm: 'Endocrine Finding 04',
    conceptClass: 'Disorder',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.4',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002125',
    fullySpecifiedName: 'Endocrine Finding entity 05 (finding)',
    preferredTerm: 'Endocrine Finding 05',
    conceptClass: 'Finding',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.5',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002142',
    fullySpecifiedName: 'Endocrine Finding entity 06 (finding)',
    preferredTerm: 'Endocrine Finding 06',
    conceptClass: 'Disorder',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.6',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002159',
    fullySpecifiedName: 'Endocrine Finding entity 07 (finding)',
    preferredTerm: 'Endocrine Finding 07',
    conceptClass: 'Finding',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.7',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002176',
    fullySpecifiedName: 'Endocrine Finding entity 08 (finding)',
    preferredTerm: 'Endocrine Finding 08',
    conceptClass: 'Disorder',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.8',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002193',
    fullySpecifiedName: 'Endocrine Finding entity 09 (finding)',
    preferredTerm: 'Endocrine Finding 09',
    conceptClass: 'Finding',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.9',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002210',
    fullySpecifiedName: 'Endocrine Finding entity 10 (finding)',
    preferredTerm: 'Endocrine Finding 10',
    conceptClass: 'Disorder',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.0',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002227',
    fullySpecifiedName: 'Endocrine Finding entity 11 (finding)',
    preferredTerm: 'Endocrine Finding 11',
    conceptClass: 'Finding',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.1',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002244',
    fullySpecifiedName: 'Endocrine Finding entity 12 (finding)',
    preferredTerm: 'Endocrine Finding 12',
    conceptClass: 'Disorder',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.2',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002261',
    fullySpecifiedName: 'Endocrine Finding entity 13 (finding)',
    preferredTerm: 'Endocrine Finding 13',
    conceptClass: 'Finding',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.3',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002278',
    fullySpecifiedName: 'Endocrine Finding entity 14 (finding)',
    preferredTerm: 'Endocrine Finding 14',
    conceptClass: 'Disorder',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.4',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002295',
    fullySpecifiedName: 'Endocrine Finding entity 15 (finding)',
    preferredTerm: 'Endocrine Finding 15',
    conceptClass: 'Finding',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.5',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002312',
    fullySpecifiedName: 'Endocrine Finding entity 16 (finding)',
    preferredTerm: 'Endocrine Finding 16',
    conceptClass: 'Disorder',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.6',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002329',
    fullySpecifiedName: 'Endocrine Finding entity 17 (finding)',
    preferredTerm: 'Endocrine Finding 17',
    conceptClass: 'Finding',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.7',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002346',
    fullySpecifiedName: 'Endocrine Finding entity 18 (finding)',
    preferredTerm: 'Endocrine Finding 18',
    conceptClass: 'Disorder',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.8',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002363',
    fullySpecifiedName: 'Endocrine Finding entity 19 (finding)',
    preferredTerm: 'Endocrine Finding 19',
    conceptClass: 'Finding',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.9',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002380',
    fullySpecifiedName: 'Endocrine Finding entity 20 (finding)',
    preferredTerm: 'Endocrine Finding 20',
    conceptClass: 'Disorder',
    clinicalDomain: 'Endocrine Finding',
    anatomicalSite: 'Pituitary, Thyroid & Adrenal',
    icd10MappingHint: 'END.0',
    clinicalDefinition: 'Standardized clinical finding representing endocrine finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002397',
    fullySpecifiedName: 'Renal Finding entity 01 (finding)',
    preferredTerm: 'Renal Finding 01',
    conceptClass: 'Finding',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.1',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002414',
    fullySpecifiedName: 'Renal Finding entity 02 (finding)',
    preferredTerm: 'Renal Finding 02',
    conceptClass: 'Disorder',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.2',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002431',
    fullySpecifiedName: 'Renal Finding entity 03 (finding)',
    preferredTerm: 'Renal Finding 03',
    conceptClass: 'Finding',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.3',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002448',
    fullySpecifiedName: 'Renal Finding entity 04 (finding)',
    preferredTerm: 'Renal Finding 04',
    conceptClass: 'Disorder',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.4',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002465',
    fullySpecifiedName: 'Renal Finding entity 05 (finding)',
    preferredTerm: 'Renal Finding 05',
    conceptClass: 'Finding',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.5',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002482',
    fullySpecifiedName: 'Renal Finding entity 06 (finding)',
    preferredTerm: 'Renal Finding 06',
    conceptClass: 'Disorder',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.6',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002499',
    fullySpecifiedName: 'Renal Finding entity 07 (finding)',
    preferredTerm: 'Renal Finding 07',
    conceptClass: 'Finding',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.7',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002516',
    fullySpecifiedName: 'Renal Finding entity 08 (finding)',
    preferredTerm: 'Renal Finding 08',
    conceptClass: 'Disorder',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.8',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002533',
    fullySpecifiedName: 'Renal Finding entity 09 (finding)',
    preferredTerm: 'Renal Finding 09',
    conceptClass: 'Finding',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.9',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002550',
    fullySpecifiedName: 'Renal Finding entity 10 (finding)',
    preferredTerm: 'Renal Finding 10',
    conceptClass: 'Disorder',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.0',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002567',
    fullySpecifiedName: 'Renal Finding entity 11 (finding)',
    preferredTerm: 'Renal Finding 11',
    conceptClass: 'Finding',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.1',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002584',
    fullySpecifiedName: 'Renal Finding entity 12 (finding)',
    preferredTerm: 'Renal Finding 12',
    conceptClass: 'Disorder',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.2',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002601',
    fullySpecifiedName: 'Renal Finding entity 13 (finding)',
    preferredTerm: 'Renal Finding 13',
    conceptClass: 'Finding',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.3',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002618',
    fullySpecifiedName: 'Renal Finding entity 14 (finding)',
    preferredTerm: 'Renal Finding 14',
    conceptClass: 'Disorder',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.4',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002635',
    fullySpecifiedName: 'Renal Finding entity 15 (finding)',
    preferredTerm: 'Renal Finding 15',
    conceptClass: 'Finding',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.5',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002652',
    fullySpecifiedName: 'Renal Finding entity 16 (finding)',
    preferredTerm: 'Renal Finding 16',
    conceptClass: 'Disorder',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.6',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002669',
    fullySpecifiedName: 'Renal Finding entity 17 (finding)',
    preferredTerm: 'Renal Finding 17',
    conceptClass: 'Finding',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.7',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002686',
    fullySpecifiedName: 'Renal Finding entity 18 (finding)',
    preferredTerm: 'Renal Finding 18',
    conceptClass: 'Disorder',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.8',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002703',
    fullySpecifiedName: 'Renal Finding entity 19 (finding)',
    preferredTerm: 'Renal Finding 19',
    conceptClass: 'Finding',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.9',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002720',
    fullySpecifiedName: 'Renal Finding entity 20 (finding)',
    preferredTerm: 'Renal Finding 20',
    conceptClass: 'Disorder',
    clinicalDomain: 'Renal Finding',
    anatomicalSite: 'Kidneys & Urinary Tract',
    icd10MappingHint: 'REN.0',
    clinicalDefinition: 'Standardized clinical finding representing renal finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002737',
    fullySpecifiedName: 'Ophthalmic Finding entity 01 (finding)',
    preferredTerm: 'Ophthalmic Finding 01',
    conceptClass: 'Finding',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.1',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002754',
    fullySpecifiedName: 'Ophthalmic Finding entity 02 (finding)',
    preferredTerm: 'Ophthalmic Finding 02',
    conceptClass: 'Disorder',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.2',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002771',
    fullySpecifiedName: 'Ophthalmic Finding entity 03 (finding)',
    preferredTerm: 'Ophthalmic Finding 03',
    conceptClass: 'Finding',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.3',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002788',
    fullySpecifiedName: 'Ophthalmic Finding entity 04 (finding)',
    preferredTerm: 'Ophthalmic Finding 04',
    conceptClass: 'Disorder',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.4',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002805',
    fullySpecifiedName: 'Ophthalmic Finding entity 05 (finding)',
    preferredTerm: 'Ophthalmic Finding 05',
    conceptClass: 'Finding',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.5',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002822',
    fullySpecifiedName: 'Ophthalmic Finding entity 06 (finding)',
    preferredTerm: 'Ophthalmic Finding 06',
    conceptClass: 'Disorder',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.6',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002839',
    fullySpecifiedName: 'Ophthalmic Finding entity 07 (finding)',
    preferredTerm: 'Ophthalmic Finding 07',
    conceptClass: 'Finding',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.7',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002856',
    fullySpecifiedName: 'Ophthalmic Finding entity 08 (finding)',
    preferredTerm: 'Ophthalmic Finding 08',
    conceptClass: 'Disorder',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.8',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002873',
    fullySpecifiedName: 'Ophthalmic Finding entity 09 (finding)',
    preferredTerm: 'Ophthalmic Finding 09',
    conceptClass: 'Finding',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.9',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002890',
    fullySpecifiedName: 'Ophthalmic Finding entity 10 (finding)',
    preferredTerm: 'Ophthalmic Finding 10',
    conceptClass: 'Disorder',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.0',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002907',
    fullySpecifiedName: 'Ophthalmic Finding entity 11 (finding)',
    preferredTerm: 'Ophthalmic Finding 11',
    conceptClass: 'Finding',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.1',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002924',
    fullySpecifiedName: 'Ophthalmic Finding entity 12 (finding)',
    preferredTerm: 'Ophthalmic Finding 12',
    conceptClass: 'Disorder',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.2',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002941',
    fullySpecifiedName: 'Ophthalmic Finding entity 13 (finding)',
    preferredTerm: 'Ophthalmic Finding 13',
    conceptClass: 'Finding',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.3',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002958',
    fullySpecifiedName: 'Ophthalmic Finding entity 14 (finding)',
    preferredTerm: 'Ophthalmic Finding 14',
    conceptClass: 'Disorder',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.4',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002975',
    fullySpecifiedName: 'Ophthalmic Finding entity 15 (finding)',
    preferredTerm: 'Ophthalmic Finding 15',
    conceptClass: 'Finding',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.5',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400002992',
    fullySpecifiedName: 'Ophthalmic Finding entity 16 (finding)',
    preferredTerm: 'Ophthalmic Finding 16',
    conceptClass: 'Disorder',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.6',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003009',
    fullySpecifiedName: 'Ophthalmic Finding entity 17 (finding)',
    preferredTerm: 'Ophthalmic Finding 17',
    conceptClass: 'Finding',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.7',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003026',
    fullySpecifiedName: 'Ophthalmic Finding entity 18 (finding)',
    preferredTerm: 'Ophthalmic Finding 18',
    conceptClass: 'Disorder',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.8',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003043',
    fullySpecifiedName: 'Ophthalmic Finding entity 19 (finding)',
    preferredTerm: 'Ophthalmic Finding 19',
    conceptClass: 'Finding',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.9',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003060',
    fullySpecifiedName: 'Ophthalmic Finding entity 20 (finding)',
    preferredTerm: 'Ophthalmic Finding 20',
    conceptClass: 'Disorder',
    clinicalDomain: 'Ophthalmic Finding',
    anatomicalSite: 'Visual System & Orbit',
    icd10MappingHint: 'OPH.0',
    clinicalDefinition: 'Standardized clinical finding representing ophthalmic finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003077',
    fullySpecifiedName: 'Psychiatric Finding entity 01 (finding)',
    preferredTerm: 'Psychiatric Finding 01',
    conceptClass: 'Finding',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.1',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003094',
    fullySpecifiedName: 'Psychiatric Finding entity 02 (finding)',
    preferredTerm: 'Psychiatric Finding 02',
    conceptClass: 'Disorder',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.2',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003111',
    fullySpecifiedName: 'Psychiatric Finding entity 03 (finding)',
    preferredTerm: 'Psychiatric Finding 03',
    conceptClass: 'Finding',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.3',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003128',
    fullySpecifiedName: 'Psychiatric Finding entity 04 (finding)',
    preferredTerm: 'Psychiatric Finding 04',
    conceptClass: 'Disorder',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.4',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003145',
    fullySpecifiedName: 'Psychiatric Finding entity 05 (finding)',
    preferredTerm: 'Psychiatric Finding 05',
    conceptClass: 'Finding',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.5',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003162',
    fullySpecifiedName: 'Psychiatric Finding entity 06 (finding)',
    preferredTerm: 'Psychiatric Finding 06',
    conceptClass: 'Disorder',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.6',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003179',
    fullySpecifiedName: 'Psychiatric Finding entity 07 (finding)',
    preferredTerm: 'Psychiatric Finding 07',
    conceptClass: 'Finding',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.7',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003196',
    fullySpecifiedName: 'Psychiatric Finding entity 08 (finding)',
    preferredTerm: 'Psychiatric Finding 08',
    conceptClass: 'Disorder',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.8',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003213',
    fullySpecifiedName: 'Psychiatric Finding entity 09 (finding)',
    preferredTerm: 'Psychiatric Finding 09',
    conceptClass: 'Finding',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.9',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003230',
    fullySpecifiedName: 'Psychiatric Finding entity 10 (finding)',
    preferredTerm: 'Psychiatric Finding 10',
    conceptClass: 'Disorder',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.0',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003247',
    fullySpecifiedName: 'Psychiatric Finding entity 11 (finding)',
    preferredTerm: 'Psychiatric Finding 11',
    conceptClass: 'Finding',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.1',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003264',
    fullySpecifiedName: 'Psychiatric Finding entity 12 (finding)',
    preferredTerm: 'Psychiatric Finding 12',
    conceptClass: 'Disorder',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.2',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003281',
    fullySpecifiedName: 'Psychiatric Finding entity 13 (finding)',
    preferredTerm: 'Psychiatric Finding 13',
    conceptClass: 'Finding',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.3',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003298',
    fullySpecifiedName: 'Psychiatric Finding entity 14 (finding)',
    preferredTerm: 'Psychiatric Finding 14',
    conceptClass: 'Disorder',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.4',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003315',
    fullySpecifiedName: 'Psychiatric Finding entity 15 (finding)',
    preferredTerm: 'Psychiatric Finding 15',
    conceptClass: 'Finding',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.5',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003332',
    fullySpecifiedName: 'Psychiatric Finding entity 16 (finding)',
    preferredTerm: 'Psychiatric Finding 16',
    conceptClass: 'Disorder',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.6',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003349',
    fullySpecifiedName: 'Psychiatric Finding entity 17 (finding)',
    preferredTerm: 'Psychiatric Finding 17',
    conceptClass: 'Finding',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.7',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003366',
    fullySpecifiedName: 'Psychiatric Finding entity 18 (finding)',
    preferredTerm: 'Psychiatric Finding 18',
    conceptClass: 'Disorder',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.8',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003383',
    fullySpecifiedName: 'Psychiatric Finding entity 19 (finding)',
    preferredTerm: 'Psychiatric Finding 19',
    conceptClass: 'Finding',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.9',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
  {
    conceptId: '400003400',
    fullySpecifiedName: 'Psychiatric Finding entity 20 (finding)',
    preferredTerm: 'Psychiatric Finding 20',
    conceptClass: 'Disorder',
    clinicalDomain: 'Psychiatric Finding',
    anatomicalSite: 'Mental Health & Cognitive',
    icd10MappingHint: 'PSY.0',
    clinicalDefinition: 'Standardized clinical finding representing psychiatric finding abnormality observed during physical examination or diagnostics.',
  },
];

export function getSNOMEDConcept(id: string): SNOMEDConcept | undefined {
  return SNOMED_CT_CONCEPTS.find((c) => c.conceptId === id);
}
