// Clinical Intake Form Definition: Cardiovascular Comprehensive Intake & NYHA Assessment
// Standard Healthcare Department: Cardiology

export interface ClinicalFormField {
  fieldId: string;
  fieldLabel: string;
  fieldType: 'TEXT' | 'NUMBER' | 'SELECT' | 'MULTISELECT' | 'BOOLEAN' | 'DATE' | 'SCALE_1_TO_10';
  clinicalDomain: string;
  isRequired: boolean;
  selectOptions?: string[];
  validationMin?: number;
  validationMax?: number;
  clinicalFlagThreshold?: string;
  guidelineHelpText: string;
}

export const CARDIOVASCULAR_INTAKE_FIELDS: ClinicalFormField[] = [
  {
    fieldId: 'FLD-CARD-01',
    fieldLabel: 'Cardiology Diagnostic Parameter 01',
    fieldType: 'NUMBER',
    clinicalDomain: 'Cardiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 1,
    validationMax: 60,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 01.',
  },
  {
    fieldId: 'FLD-CARD-02',
    fieldLabel: 'Cardiology Diagnostic Parameter 02',
    fieldType: 'SELECT',
    clinicalDomain: 'Cardiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 2,
    validationMax: 70,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 02.',
  },
  {
    fieldId: 'FLD-CARD-03',
    fieldLabel: 'Cardiology Diagnostic Parameter 03',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Cardiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 3,
    validationMax: 80,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 03.',
  },
  {
    fieldId: 'FLD-CARD-04',
    fieldLabel: 'Cardiology Diagnostic Parameter 04',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Cardiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 4,
    validationMax: 90,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 04.',
  },
  {
    fieldId: 'FLD-CARD-05',
    fieldLabel: 'Cardiology Diagnostic Parameter 05',
    fieldType: 'TEXT',
    clinicalDomain: 'Cardiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 5,
    validationMax: 100,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 05.',
  },
  {
    fieldId: 'FLD-CARD-06',
    fieldLabel: 'Cardiology Diagnostic Parameter 06',
    fieldType: 'NUMBER',
    clinicalDomain: 'Cardiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 6,
    validationMax: 110,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 06.',
  },
  {
    fieldId: 'FLD-CARD-07',
    fieldLabel: 'Cardiology Diagnostic Parameter 07',
    fieldType: 'SELECT',
    clinicalDomain: 'Cardiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 7,
    validationMax: 120,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 07.',
  },
  {
    fieldId: 'FLD-CARD-08',
    fieldLabel: 'Cardiology Diagnostic Parameter 08',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Cardiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 8,
    validationMax: 130,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 08.',
  },
  {
    fieldId: 'FLD-CARD-09',
    fieldLabel: 'Cardiology Diagnostic Parameter 09',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Cardiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 9,
    validationMax: 140,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 09.',
  },
  {
    fieldId: 'FLD-CARD-10',
    fieldLabel: 'Cardiology Diagnostic Parameter 10',
    fieldType: 'TEXT',
    clinicalDomain: 'Cardiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 10,
    validationMax: 150,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 10.',
  },
  {
    fieldId: 'FLD-CARD-11',
    fieldLabel: 'Cardiology Diagnostic Parameter 11',
    fieldType: 'NUMBER',
    clinicalDomain: 'Cardiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 11,
    validationMax: 160,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 11.',
  },
  {
    fieldId: 'FLD-CARD-12',
    fieldLabel: 'Cardiology Diagnostic Parameter 12',
    fieldType: 'SELECT',
    clinicalDomain: 'Cardiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 12,
    validationMax: 170,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 12.',
  },
  {
    fieldId: 'FLD-CARD-13',
    fieldLabel: 'Cardiology Diagnostic Parameter 13',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Cardiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 13,
    validationMax: 180,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 13.',
  },
  {
    fieldId: 'FLD-CARD-14',
    fieldLabel: 'Cardiology Diagnostic Parameter 14',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Cardiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 14,
    validationMax: 190,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 14.',
  },
  {
    fieldId: 'FLD-CARD-15',
    fieldLabel: 'Cardiology Diagnostic Parameter 15',
    fieldType: 'TEXT',
    clinicalDomain: 'Cardiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 15,
    validationMax: 200,
    clinicalFlagThreshold: 'Value exceeds standard cardiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for cardiology parameter 15.',
  },
];

export function getCardiovascularIntakeField(id: string): ClinicalFormField | undefined {
  return CARDIOVASCULAR_INTAKE_FIELDS.find((f) => f.fieldId === id);
}
