// Clinical Intake Form Definition: Dermatological Lesion Inventory & ABCDE Staging
// Standard Healthcare Department: Dermatology

export interface ClinicalFormField {
  fieldId: string;
  fieldLabel: string;
  fieldType: 'TEXT' | 'NUMBER' | 'SELECT' | 'MULTISELECT' | 'BOOLEAN' | 'DATE' | 'SCALE_1_TO_10';
  clinicalDomain: string;
  isRequired: boolean;
  selectOptions?: string[];
  validationMin?: number;
  validationMax?: number;
  clinicalFlagThreshold?: string;
  guidelineHelpText: string;
}

export const DERMATOLOGY_LESION_FIELDS: ClinicalFormField[] = [
  {
    fieldId: 'FLD-DERM-01',
    fieldLabel: 'Dermatology Diagnostic Parameter 01',
    fieldType: 'NUMBER',
    clinicalDomain: 'Dermatology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 1,
    validationMax: 60,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 01.',
  },
  {
    fieldId: 'FLD-DERM-02',
    fieldLabel: 'Dermatology Diagnostic Parameter 02',
    fieldType: 'SELECT',
    clinicalDomain: 'Dermatology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 2,
    validationMax: 70,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 02.',
  },
  {
    fieldId: 'FLD-DERM-03',
    fieldLabel: 'Dermatology Diagnostic Parameter 03',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Dermatology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 3,
    validationMax: 80,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 03.',
  },
  {
    fieldId: 'FLD-DERM-04',
    fieldLabel: 'Dermatology Diagnostic Parameter 04',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Dermatology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 4,
    validationMax: 90,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 04.',
  },
  {
    fieldId: 'FLD-DERM-05',
    fieldLabel: 'Dermatology Diagnostic Parameter 05',
    fieldType: 'TEXT',
    clinicalDomain: 'Dermatology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 5,
    validationMax: 100,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 05.',
  },
  {
    fieldId: 'FLD-DERM-06',
    fieldLabel: 'Dermatology Diagnostic Parameter 06',
    fieldType: 'NUMBER',
    clinicalDomain: 'Dermatology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 6,
    validationMax: 110,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 06.',
  },
  {
    fieldId: 'FLD-DERM-07',
    fieldLabel: 'Dermatology Diagnostic Parameter 07',
    fieldType: 'SELECT',
    clinicalDomain: 'Dermatology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 7,
    validationMax: 120,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 07.',
  },
  {
    fieldId: 'FLD-DERM-08',
    fieldLabel: 'Dermatology Diagnostic Parameter 08',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Dermatology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 8,
    validationMax: 130,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 08.',
  },
  {
    fieldId: 'FLD-DERM-09',
    fieldLabel: 'Dermatology Diagnostic Parameter 09',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Dermatology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 9,
    validationMax: 140,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 09.',
  },
  {
    fieldId: 'FLD-DERM-10',
    fieldLabel: 'Dermatology Diagnostic Parameter 10',
    fieldType: 'TEXT',
    clinicalDomain: 'Dermatology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 10,
    validationMax: 150,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 10.',
  },
  {
    fieldId: 'FLD-DERM-11',
    fieldLabel: 'Dermatology Diagnostic Parameter 11',
    fieldType: 'NUMBER',
    clinicalDomain: 'Dermatology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 11,
    validationMax: 160,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 11.',
  },
  {
    fieldId: 'FLD-DERM-12',
    fieldLabel: 'Dermatology Diagnostic Parameter 12',
    fieldType: 'SELECT',
    clinicalDomain: 'Dermatology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 12,
    validationMax: 170,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 12.',
  },
  {
    fieldId: 'FLD-DERM-13',
    fieldLabel: 'Dermatology Diagnostic Parameter 13',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Dermatology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 13,
    validationMax: 180,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 13.',
  },
  {
    fieldId: 'FLD-DERM-14',
    fieldLabel: 'Dermatology Diagnostic Parameter 14',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Dermatology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 14,
    validationMax: 190,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 14.',
  },
  {
    fieldId: 'FLD-DERM-15',
    fieldLabel: 'Dermatology Diagnostic Parameter 15',
    fieldType: 'TEXT',
    clinicalDomain: 'Dermatology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 15,
    validationMax: 200,
    clinicalFlagThreshold: 'Value exceeds standard dermatology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for dermatology parameter 15.',
  },
];

export function getDermatologyLesionField(id: string): ClinicalFormField | undefined {
  return DERMATOLOGY_LESION_FIELDS.find((f) => f.fieldId === id);
}
