// Clinical Intake Form Definition: Diabetes Self-Management & Glycemic Diary Inventory
// Standard Healthcare Department: Endocrinology

export interface ClinicalFormField {
  fieldId: string;
  fieldLabel: string;
  fieldType: 'TEXT' | 'NUMBER' | 'SELECT' | 'MULTISELECT' | 'BOOLEAN' | 'DATE' | 'SCALE_1_TO_10';
  clinicalDomain: string;
  isRequired: boolean;
  selectOptions?: string[];
  validationMin?: number;
  validationMax?: number;
  clinicalFlagThreshold?: string;
  guidelineHelpText: string;
}

export const ENDOCRINOLOGY_DIABETES_FIELDS: ClinicalFormField[] = [
  {
    fieldId: 'FLD-ENDO-01',
    fieldLabel: 'Endocrinology Diagnostic Parameter 01',
    fieldType: 'NUMBER',
    clinicalDomain: 'Endocrinology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 1,
    validationMax: 60,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 01.',
  },
  {
    fieldId: 'FLD-ENDO-02',
    fieldLabel: 'Endocrinology Diagnostic Parameter 02',
    fieldType: 'SELECT',
    clinicalDomain: 'Endocrinology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 2,
    validationMax: 70,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 02.',
  },
  {
    fieldId: 'FLD-ENDO-03',
    fieldLabel: 'Endocrinology Diagnostic Parameter 03',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Endocrinology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 3,
    validationMax: 80,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 03.',
  },
  {
    fieldId: 'FLD-ENDO-04',
    fieldLabel: 'Endocrinology Diagnostic Parameter 04',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Endocrinology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 4,
    validationMax: 90,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 04.',
  },
  {
    fieldId: 'FLD-ENDO-05',
    fieldLabel: 'Endocrinology Diagnostic Parameter 05',
    fieldType: 'TEXT',
    clinicalDomain: 'Endocrinology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 5,
    validationMax: 100,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 05.',
  },
  {
    fieldId: 'FLD-ENDO-06',
    fieldLabel: 'Endocrinology Diagnostic Parameter 06',
    fieldType: 'NUMBER',
    clinicalDomain: 'Endocrinology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 6,
    validationMax: 110,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 06.',
  },
  {
    fieldId: 'FLD-ENDO-07',
    fieldLabel: 'Endocrinology Diagnostic Parameter 07',
    fieldType: 'SELECT',
    clinicalDomain: 'Endocrinology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 7,
    validationMax: 120,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 07.',
  },
  {
    fieldId: 'FLD-ENDO-08',
    fieldLabel: 'Endocrinology Diagnostic Parameter 08',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Endocrinology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 8,
    validationMax: 130,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 08.',
  },
  {
    fieldId: 'FLD-ENDO-09',
    fieldLabel: 'Endocrinology Diagnostic Parameter 09',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Endocrinology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 9,
    validationMax: 140,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 09.',
  },
  {
    fieldId: 'FLD-ENDO-10',
    fieldLabel: 'Endocrinology Diagnostic Parameter 10',
    fieldType: 'TEXT',
    clinicalDomain: 'Endocrinology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 10,
    validationMax: 150,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 10.',
  },
  {
    fieldId: 'FLD-ENDO-11',
    fieldLabel: 'Endocrinology Diagnostic Parameter 11',
    fieldType: 'NUMBER',
    clinicalDomain: 'Endocrinology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 11,
    validationMax: 160,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 11.',
  },
  {
    fieldId: 'FLD-ENDO-12',
    fieldLabel: 'Endocrinology Diagnostic Parameter 12',
    fieldType: 'SELECT',
    clinicalDomain: 'Endocrinology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 12,
    validationMax: 170,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 12.',
  },
  {
    fieldId: 'FLD-ENDO-13',
    fieldLabel: 'Endocrinology Diagnostic Parameter 13',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Endocrinology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 13,
    validationMax: 180,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 13.',
  },
  {
    fieldId: 'FLD-ENDO-14',
    fieldLabel: 'Endocrinology Diagnostic Parameter 14',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Endocrinology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 14,
    validationMax: 190,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 14.',
  },
  {
    fieldId: 'FLD-ENDO-15',
    fieldLabel: 'Endocrinology Diagnostic Parameter 15',
    fieldType: 'TEXT',
    clinicalDomain: 'Endocrinology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 15,
    validationMax: 200,
    clinicalFlagThreshold: 'Value exceeds standard endocrinology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for endocrinology parameter 15.',
  },
];

export function getEndocrinologyDiabetesField(id: string): ClinicalFormField | undefined {
  return ENDOCRINOLOGY_DIABETES_FIELDS.find((f) => f.fieldId === id);
}
