// Clinical Intake Form Definition: Gastrointestinal Symptom & Liver Function Assessment
// Standard Healthcare Department: Gastroenterology

export interface ClinicalFormField {
  fieldId: string;
  fieldLabel: string;
  fieldType: 'TEXT' | 'NUMBER' | 'SELECT' | 'MULTISELECT' | 'BOOLEAN' | 'DATE' | 'SCALE_1_TO_10';
  clinicalDomain: string;
  isRequired: boolean;
  selectOptions?: string[];
  validationMin?: number;
  validationMax?: number;
  clinicalFlagThreshold?: string;
  guidelineHelpText: string;
}

export const GASTROENTEROLOGY_INTAKE_FIELDS: ClinicalFormField[] = [
  {
    fieldId: 'FLD-GAST-01',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 01',
    fieldType: 'NUMBER',
    clinicalDomain: 'Gastroenterology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 1,
    validationMax: 60,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 01.',
  },
  {
    fieldId: 'FLD-GAST-02',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 02',
    fieldType: 'SELECT',
    clinicalDomain: 'Gastroenterology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 2,
    validationMax: 70,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 02.',
  },
  {
    fieldId: 'FLD-GAST-03',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 03',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Gastroenterology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 3,
    validationMax: 80,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 03.',
  },
  {
    fieldId: 'FLD-GAST-04',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 04',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Gastroenterology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 4,
    validationMax: 90,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 04.',
  },
  {
    fieldId: 'FLD-GAST-05',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 05',
    fieldType: 'TEXT',
    clinicalDomain: 'Gastroenterology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 5,
    validationMax: 100,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 05.',
  },
  {
    fieldId: 'FLD-GAST-06',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 06',
    fieldType: 'NUMBER',
    clinicalDomain: 'Gastroenterology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 6,
    validationMax: 110,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 06.',
  },
  {
    fieldId: 'FLD-GAST-07',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 07',
    fieldType: 'SELECT',
    clinicalDomain: 'Gastroenterology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 7,
    validationMax: 120,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 07.',
  },
  {
    fieldId: 'FLD-GAST-08',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 08',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Gastroenterology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 8,
    validationMax: 130,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 08.',
  },
  {
    fieldId: 'FLD-GAST-09',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 09',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Gastroenterology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 9,
    validationMax: 140,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 09.',
  },
  {
    fieldId: 'FLD-GAST-10',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 10',
    fieldType: 'TEXT',
    clinicalDomain: 'Gastroenterology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 10,
    validationMax: 150,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 10.',
  },
  {
    fieldId: 'FLD-GAST-11',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 11',
    fieldType: 'NUMBER',
    clinicalDomain: 'Gastroenterology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 11,
    validationMax: 160,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 11.',
  },
  {
    fieldId: 'FLD-GAST-12',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 12',
    fieldType: 'SELECT',
    clinicalDomain: 'Gastroenterology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 12,
    validationMax: 170,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 12.',
  },
  {
    fieldId: 'FLD-GAST-13',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 13',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Gastroenterology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 13,
    validationMax: 180,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 13.',
  },
  {
    fieldId: 'FLD-GAST-14',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 14',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Gastroenterology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 14,
    validationMax: 190,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 14.',
  },
  {
    fieldId: 'FLD-GAST-15',
    fieldLabel: 'Gastroenterology Diagnostic Parameter 15',
    fieldType: 'TEXT',
    clinicalDomain: 'Gastroenterology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 15,
    validationMax: 200,
    clinicalFlagThreshold: 'Value exceeds standard gastroenterology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for gastroenterology parameter 15.',
  },
];

export function getGastroenterologyIntakeField(id: string): ClinicalFormField | undefined {
  return GASTROENTEROLOGY_INTAKE_FIELDS.find((f) => f.fieldId === id);
}
