// Clinical Intake Form Definition: Comprehensive Neurological Exam & Cranial Nerve Inventory
// Standard Healthcare Department: Neurology

export interface ClinicalFormField {
  fieldId: string;
  fieldLabel: string;
  fieldType: 'TEXT' | 'NUMBER' | 'SELECT' | 'MULTISELECT' | 'BOOLEAN' | 'DATE' | 'SCALE_1_TO_10';
  clinicalDomain: string;
  isRequired: boolean;
  selectOptions?: string[];
  validationMin?: number;
  validationMax?: number;
  clinicalFlagThreshold?: string;
  guidelineHelpText: string;
}

export const NEUROLOGICAL_ASSESSMENT_FIELDS: ClinicalFormField[] = [
  {
    fieldId: 'FLD-NEUR-01',
    fieldLabel: 'Neurology Diagnostic Parameter 01',
    fieldType: 'NUMBER',
    clinicalDomain: 'Neurology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 1,
    validationMax: 60,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 01.',
  },
  {
    fieldId: 'FLD-NEUR-02',
    fieldLabel: 'Neurology Diagnostic Parameter 02',
    fieldType: 'SELECT',
    clinicalDomain: 'Neurology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 2,
    validationMax: 70,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 02.',
  },
  {
    fieldId: 'FLD-NEUR-03',
    fieldLabel: 'Neurology Diagnostic Parameter 03',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Neurology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 3,
    validationMax: 80,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 03.',
  },
  {
    fieldId: 'FLD-NEUR-04',
    fieldLabel: 'Neurology Diagnostic Parameter 04',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Neurology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 4,
    validationMax: 90,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 04.',
  },
  {
    fieldId: 'FLD-NEUR-05',
    fieldLabel: 'Neurology Diagnostic Parameter 05',
    fieldType: 'TEXT',
    clinicalDomain: 'Neurology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 5,
    validationMax: 100,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 05.',
  },
  {
    fieldId: 'FLD-NEUR-06',
    fieldLabel: 'Neurology Diagnostic Parameter 06',
    fieldType: 'NUMBER',
    clinicalDomain: 'Neurology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 6,
    validationMax: 110,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 06.',
  },
  {
    fieldId: 'FLD-NEUR-07',
    fieldLabel: 'Neurology Diagnostic Parameter 07',
    fieldType: 'SELECT',
    clinicalDomain: 'Neurology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 7,
    validationMax: 120,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 07.',
  },
  {
    fieldId: 'FLD-NEUR-08',
    fieldLabel: 'Neurology Diagnostic Parameter 08',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Neurology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 8,
    validationMax: 130,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 08.',
  },
  {
    fieldId: 'FLD-NEUR-09',
    fieldLabel: 'Neurology Diagnostic Parameter 09',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Neurology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 9,
    validationMax: 140,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 09.',
  },
  {
    fieldId: 'FLD-NEUR-10',
    fieldLabel: 'Neurology Diagnostic Parameter 10',
    fieldType: 'TEXT',
    clinicalDomain: 'Neurology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 10,
    validationMax: 150,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 10.',
  },
  {
    fieldId: 'FLD-NEUR-11',
    fieldLabel: 'Neurology Diagnostic Parameter 11',
    fieldType: 'NUMBER',
    clinicalDomain: 'Neurology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 11,
    validationMax: 160,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 11.',
  },
  {
    fieldId: 'FLD-NEUR-12',
    fieldLabel: 'Neurology Diagnostic Parameter 12',
    fieldType: 'SELECT',
    clinicalDomain: 'Neurology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 12,
    validationMax: 170,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 12.',
  },
  {
    fieldId: 'FLD-NEUR-13',
    fieldLabel: 'Neurology Diagnostic Parameter 13',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Neurology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 13,
    validationMax: 180,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 13.',
  },
  {
    fieldId: 'FLD-NEUR-14',
    fieldLabel: 'Neurology Diagnostic Parameter 14',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Neurology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 14,
    validationMax: 190,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 14.',
  },
  {
    fieldId: 'FLD-NEUR-15',
    fieldLabel: 'Neurology Diagnostic Parameter 15',
    fieldType: 'TEXT',
    clinicalDomain: 'Neurology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 15,
    validationMax: 200,
    clinicalFlagThreshold: 'Value exceeds standard neurology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for neurology parameter 15.',
  },
];

export function getNeurologicalAssessmentField(id: string): ClinicalFormField | undefined {
  return NEUROLOGICAL_ASSESSMENT_FIELDS.find((f) => f.fieldId === id);
}
