// Clinical Intake Form Definition: Oncology Clinical Staging & Performance Status (ECOG)
// Standard Healthcare Department: Oncology

export interface ClinicalFormField {
  fieldId: string;
  fieldLabel: string;
  fieldType: 'TEXT' | 'NUMBER' | 'SELECT' | 'MULTISELECT' | 'BOOLEAN' | 'DATE' | 'SCALE_1_TO_10';
  clinicalDomain: string;
  isRequired: boolean;
  selectOptions?: string[];
  validationMin?: number;
  validationMax?: number;
  clinicalFlagThreshold?: string;
  guidelineHelpText: string;
}

export const ONCOLOGY_INTAKE_FIELDS: ClinicalFormField[] = [
  {
    fieldId: 'FLD-ONCO-01',
    fieldLabel: 'Oncology Diagnostic Parameter 01',
    fieldType: 'NUMBER',
    clinicalDomain: 'Oncology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 1,
    validationMax: 60,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 01.',
  },
  {
    fieldId: 'FLD-ONCO-02',
    fieldLabel: 'Oncology Diagnostic Parameter 02',
    fieldType: 'SELECT',
    clinicalDomain: 'Oncology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 2,
    validationMax: 70,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 02.',
  },
  {
    fieldId: 'FLD-ONCO-03',
    fieldLabel: 'Oncology Diagnostic Parameter 03',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Oncology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 3,
    validationMax: 80,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 03.',
  },
  {
    fieldId: 'FLD-ONCO-04',
    fieldLabel: 'Oncology Diagnostic Parameter 04',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Oncology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 4,
    validationMax: 90,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 04.',
  },
  {
    fieldId: 'FLD-ONCO-05',
    fieldLabel: 'Oncology Diagnostic Parameter 05',
    fieldType: 'TEXT',
    clinicalDomain: 'Oncology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 5,
    validationMax: 100,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 05.',
  },
  {
    fieldId: 'FLD-ONCO-06',
    fieldLabel: 'Oncology Diagnostic Parameter 06',
    fieldType: 'NUMBER',
    clinicalDomain: 'Oncology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 6,
    validationMax: 110,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 06.',
  },
  {
    fieldId: 'FLD-ONCO-07',
    fieldLabel: 'Oncology Diagnostic Parameter 07',
    fieldType: 'SELECT',
    clinicalDomain: 'Oncology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 7,
    validationMax: 120,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 07.',
  },
  {
    fieldId: 'FLD-ONCO-08',
    fieldLabel: 'Oncology Diagnostic Parameter 08',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Oncology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 8,
    validationMax: 130,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 08.',
  },
  {
    fieldId: 'FLD-ONCO-09',
    fieldLabel: 'Oncology Diagnostic Parameter 09',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Oncology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 9,
    validationMax: 140,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 09.',
  },
  {
    fieldId: 'FLD-ONCO-10',
    fieldLabel: 'Oncology Diagnostic Parameter 10',
    fieldType: 'TEXT',
    clinicalDomain: 'Oncology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 10,
    validationMax: 150,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 10.',
  },
  {
    fieldId: 'FLD-ONCO-11',
    fieldLabel: 'Oncology Diagnostic Parameter 11',
    fieldType: 'NUMBER',
    clinicalDomain: 'Oncology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 11,
    validationMax: 160,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 11.',
  },
  {
    fieldId: 'FLD-ONCO-12',
    fieldLabel: 'Oncology Diagnostic Parameter 12',
    fieldType: 'SELECT',
    clinicalDomain: 'Oncology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 12,
    validationMax: 170,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 12.',
  },
  {
    fieldId: 'FLD-ONCO-13',
    fieldLabel: 'Oncology Diagnostic Parameter 13',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Oncology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 13,
    validationMax: 180,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 13.',
  },
  {
    fieldId: 'FLD-ONCO-14',
    fieldLabel: 'Oncology Diagnostic Parameter 14',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Oncology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 14,
    validationMax: 190,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 14.',
  },
  {
    fieldId: 'FLD-ONCO-15',
    fieldLabel: 'Oncology Diagnostic Parameter 15',
    fieldType: 'TEXT',
    clinicalDomain: 'Oncology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 15,
    validationMax: 200,
    clinicalFlagThreshold: 'Value exceeds standard oncology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for oncology parameter 15.',
  },
];

export function getOncologyIntakeField(id: string): ClinicalFormField | undefined {
  return ONCOLOGY_INTAKE_FIELDS.find((f) => f.fieldId === id);
}
