// Clinical Intake Form Definition: Musculoskeletal Range of Motion & WOMAC Index
// Standard Healthcare Department: Orthopedics

export interface ClinicalFormField {
  fieldId: string;
  fieldLabel: string;
  fieldType: 'TEXT' | 'NUMBER' | 'SELECT' | 'MULTISELECT' | 'BOOLEAN' | 'DATE' | 'SCALE_1_TO_10';
  clinicalDomain: string;
  isRequired: boolean;
  selectOptions?: string[];
  validationMin?: number;
  validationMax?: number;
  clinicalFlagThreshold?: string;
  guidelineHelpText: string;
}

export const ORTHOPEDIC_FUNCTIONAL_FIELDS: ClinicalFormField[] = [
  {
    fieldId: 'FLD-ORTH-01',
    fieldLabel: 'Orthopedics Diagnostic Parameter 01',
    fieldType: 'NUMBER',
    clinicalDomain: 'Orthopedics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 1,
    validationMax: 60,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 01.',
  },
  {
    fieldId: 'FLD-ORTH-02',
    fieldLabel: 'Orthopedics Diagnostic Parameter 02',
    fieldType: 'SELECT',
    clinicalDomain: 'Orthopedics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 2,
    validationMax: 70,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 02.',
  },
  {
    fieldId: 'FLD-ORTH-03',
    fieldLabel: 'Orthopedics Diagnostic Parameter 03',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Orthopedics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 3,
    validationMax: 80,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 03.',
  },
  {
    fieldId: 'FLD-ORTH-04',
    fieldLabel: 'Orthopedics Diagnostic Parameter 04',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Orthopedics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 4,
    validationMax: 90,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 04.',
  },
  {
    fieldId: 'FLD-ORTH-05',
    fieldLabel: 'Orthopedics Diagnostic Parameter 05',
    fieldType: 'TEXT',
    clinicalDomain: 'Orthopedics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 5,
    validationMax: 100,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 05.',
  },
  {
    fieldId: 'FLD-ORTH-06',
    fieldLabel: 'Orthopedics Diagnostic Parameter 06',
    fieldType: 'NUMBER',
    clinicalDomain: 'Orthopedics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 6,
    validationMax: 110,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 06.',
  },
  {
    fieldId: 'FLD-ORTH-07',
    fieldLabel: 'Orthopedics Diagnostic Parameter 07',
    fieldType: 'SELECT',
    clinicalDomain: 'Orthopedics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 7,
    validationMax: 120,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 07.',
  },
  {
    fieldId: 'FLD-ORTH-08',
    fieldLabel: 'Orthopedics Diagnostic Parameter 08',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Orthopedics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 8,
    validationMax: 130,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 08.',
  },
  {
    fieldId: 'FLD-ORTH-09',
    fieldLabel: 'Orthopedics Diagnostic Parameter 09',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Orthopedics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 9,
    validationMax: 140,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 09.',
  },
  {
    fieldId: 'FLD-ORTH-10',
    fieldLabel: 'Orthopedics Diagnostic Parameter 10',
    fieldType: 'TEXT',
    clinicalDomain: 'Orthopedics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 10,
    validationMax: 150,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 10.',
  },
  {
    fieldId: 'FLD-ORTH-11',
    fieldLabel: 'Orthopedics Diagnostic Parameter 11',
    fieldType: 'NUMBER',
    clinicalDomain: 'Orthopedics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 11,
    validationMax: 160,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 11.',
  },
  {
    fieldId: 'FLD-ORTH-12',
    fieldLabel: 'Orthopedics Diagnostic Parameter 12',
    fieldType: 'SELECT',
    clinicalDomain: 'Orthopedics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 12,
    validationMax: 170,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 12.',
  },
  {
    fieldId: 'FLD-ORTH-13',
    fieldLabel: 'Orthopedics Diagnostic Parameter 13',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Orthopedics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 13,
    validationMax: 180,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 13.',
  },
  {
    fieldId: 'FLD-ORTH-14',
    fieldLabel: 'Orthopedics Diagnostic Parameter 14',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Orthopedics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 14,
    validationMax: 190,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 14.',
  },
  {
    fieldId: 'FLD-ORTH-15',
    fieldLabel: 'Orthopedics Diagnostic Parameter 15',
    fieldType: 'TEXT',
    clinicalDomain: 'Orthopedics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 15,
    validationMax: 200,
    clinicalFlagThreshold: 'Value exceeds standard orthopedics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for orthopedics parameter 15.',
  },
];

export function getOrthopedicFunctionalField(id: string): ClinicalFormField | undefined {
  return ORTHOPEDIC_FUNCTIONAL_FIELDS.find((f) => f.fieldId === id);
}
