// Clinical Intake Form Definition: Pediatric Developmental Milestones & Well-Child Check
// Standard Healthcare Department: Pediatrics

export interface ClinicalFormField {
  fieldId: string;
  fieldLabel: string;
  fieldType: 'TEXT' | 'NUMBER' | 'SELECT' | 'MULTISELECT' | 'BOOLEAN' | 'DATE' | 'SCALE_1_TO_10';
  clinicalDomain: string;
  isRequired: boolean;
  selectOptions?: string[];
  validationMin?: number;
  validationMax?: number;
  clinicalFlagThreshold?: string;
  guidelineHelpText: string;
}

export const PEDIATRIC_WELLCHILD_FIELDS: ClinicalFormField[] = [
  {
    fieldId: 'FLD-PEDI-01',
    fieldLabel: 'Pediatrics Diagnostic Parameter 01',
    fieldType: 'NUMBER',
    clinicalDomain: 'Pediatrics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 1,
    validationMax: 60,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 01.',
  },
  {
    fieldId: 'FLD-PEDI-02',
    fieldLabel: 'Pediatrics Diagnostic Parameter 02',
    fieldType: 'SELECT',
    clinicalDomain: 'Pediatrics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 2,
    validationMax: 70,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 02.',
  },
  {
    fieldId: 'FLD-PEDI-03',
    fieldLabel: 'Pediatrics Diagnostic Parameter 03',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Pediatrics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 3,
    validationMax: 80,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 03.',
  },
  {
    fieldId: 'FLD-PEDI-04',
    fieldLabel: 'Pediatrics Diagnostic Parameter 04',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Pediatrics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 4,
    validationMax: 90,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 04.',
  },
  {
    fieldId: 'FLD-PEDI-05',
    fieldLabel: 'Pediatrics Diagnostic Parameter 05',
    fieldType: 'TEXT',
    clinicalDomain: 'Pediatrics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 5,
    validationMax: 100,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 05.',
  },
  {
    fieldId: 'FLD-PEDI-06',
    fieldLabel: 'Pediatrics Diagnostic Parameter 06',
    fieldType: 'NUMBER',
    clinicalDomain: 'Pediatrics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 6,
    validationMax: 110,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 06.',
  },
  {
    fieldId: 'FLD-PEDI-07',
    fieldLabel: 'Pediatrics Diagnostic Parameter 07',
    fieldType: 'SELECT',
    clinicalDomain: 'Pediatrics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 7,
    validationMax: 120,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 07.',
  },
  {
    fieldId: 'FLD-PEDI-08',
    fieldLabel: 'Pediatrics Diagnostic Parameter 08',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Pediatrics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 8,
    validationMax: 130,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 08.',
  },
  {
    fieldId: 'FLD-PEDI-09',
    fieldLabel: 'Pediatrics Diagnostic Parameter 09',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Pediatrics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 9,
    validationMax: 140,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 09.',
  },
  {
    fieldId: 'FLD-PEDI-10',
    fieldLabel: 'Pediatrics Diagnostic Parameter 10',
    fieldType: 'TEXT',
    clinicalDomain: 'Pediatrics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 10,
    validationMax: 150,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 10.',
  },
  {
    fieldId: 'FLD-PEDI-11',
    fieldLabel: 'Pediatrics Diagnostic Parameter 11',
    fieldType: 'NUMBER',
    clinicalDomain: 'Pediatrics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 11,
    validationMax: 160,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 11.',
  },
  {
    fieldId: 'FLD-PEDI-12',
    fieldLabel: 'Pediatrics Diagnostic Parameter 12',
    fieldType: 'SELECT',
    clinicalDomain: 'Pediatrics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 12,
    validationMax: 170,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 12.',
  },
  {
    fieldId: 'FLD-PEDI-13',
    fieldLabel: 'Pediatrics Diagnostic Parameter 13',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Pediatrics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 13,
    validationMax: 180,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 13.',
  },
  {
    fieldId: 'FLD-PEDI-14',
    fieldLabel: 'Pediatrics Diagnostic Parameter 14',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Pediatrics',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 14,
    validationMax: 190,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 14.',
  },
  {
    fieldId: 'FLD-PEDI-15',
    fieldLabel: 'Pediatrics Diagnostic Parameter 15',
    fieldType: 'TEXT',
    clinicalDomain: 'Pediatrics',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 15,
    validationMax: 200,
    clinicalFlagThreshold: 'Value exceeds standard pediatrics safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for pediatrics parameter 15.',
  },
];

export function getPediatricWellchildField(id: string): ClinicalFormField | undefined {
  return PEDIATRIC_WELLCHILD_FIELDS.find((f) => f.fieldId === id);
}
