// Clinical Intake Form Definition: Anesthesia Risk Assessment & Pre-Surgical Clearance
// Standard Healthcare Department: Anesthesiology

export interface ClinicalFormField {
  fieldId: string;
  fieldLabel: string;
  fieldType: 'TEXT' | 'NUMBER' | 'SELECT' | 'MULTISELECT' | 'BOOLEAN' | 'DATE' | 'SCALE_1_TO_10';
  clinicalDomain: string;
  isRequired: boolean;
  selectOptions?: string[];
  validationMin?: number;
  validationMax?: number;
  clinicalFlagThreshold?: string;
  guidelineHelpText: string;
}

export const PREOPERATIVE_CLEARANCE_FIELDS: ClinicalFormField[] = [
  {
    fieldId: 'FLD-PREO-01',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 01',
    fieldType: 'NUMBER',
    clinicalDomain: 'Anesthesiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 1,
    validationMax: 60,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 01.',
  },
  {
    fieldId: 'FLD-PREO-02',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 02',
    fieldType: 'SELECT',
    clinicalDomain: 'Anesthesiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 2,
    validationMax: 70,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 02.',
  },
  {
    fieldId: 'FLD-PREO-03',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 03',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Anesthesiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 3,
    validationMax: 80,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 03.',
  },
  {
    fieldId: 'FLD-PREO-04',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 04',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Anesthesiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 4,
    validationMax: 90,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 04.',
  },
  {
    fieldId: 'FLD-PREO-05',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 05',
    fieldType: 'TEXT',
    clinicalDomain: 'Anesthesiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 5,
    validationMax: 100,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 05.',
  },
  {
    fieldId: 'FLD-PREO-06',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 06',
    fieldType: 'NUMBER',
    clinicalDomain: 'Anesthesiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 6,
    validationMax: 110,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 06.',
  },
  {
    fieldId: 'FLD-PREO-07',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 07',
    fieldType: 'SELECT',
    clinicalDomain: 'Anesthesiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 7,
    validationMax: 120,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 07.',
  },
  {
    fieldId: 'FLD-PREO-08',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 08',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Anesthesiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 8,
    validationMax: 130,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 08.',
  },
  {
    fieldId: 'FLD-PREO-09',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 09',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Anesthesiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 9,
    validationMax: 140,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 09.',
  },
  {
    fieldId: 'FLD-PREO-10',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 10',
    fieldType: 'TEXT',
    clinicalDomain: 'Anesthesiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 10,
    validationMax: 150,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 10.',
  },
  {
    fieldId: 'FLD-PREO-11',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 11',
    fieldType: 'NUMBER',
    clinicalDomain: 'Anesthesiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 11,
    validationMax: 160,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 11.',
  },
  {
    fieldId: 'FLD-PREO-12',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 12',
    fieldType: 'SELECT',
    clinicalDomain: 'Anesthesiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 12,
    validationMax: 170,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 12.',
  },
  {
    fieldId: 'FLD-PREO-13',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 13',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Anesthesiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 13,
    validationMax: 180,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 13.',
  },
  {
    fieldId: 'FLD-PREO-14',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 14',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Anesthesiology',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 14,
    validationMax: 190,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 14.',
  },
  {
    fieldId: 'FLD-PREO-15',
    fieldLabel: 'Anesthesiology Diagnostic Parameter 15',
    fieldType: 'TEXT',
    clinicalDomain: 'Anesthesiology',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 15,
    validationMax: 200,
    clinicalFlagThreshold: 'Value exceeds standard anesthesiology safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for anesthesiology parameter 15.',
  },
];

export function getPreoperativeClearanceField(id: string): ClinicalFormField | undefined {
  return PREOPERATIVE_CLEARANCE_FIELDS.find((f) => f.fieldId === id);
}
