// Clinical Intake Form Definition: Psychiatric Evaluation, PHQ-9 & GAD-7 Standard Scoring
// Standard Healthcare Department: Psychiatry

export interface ClinicalFormField {
  fieldId: string;
  fieldLabel: string;
  fieldType: 'TEXT' | 'NUMBER' | 'SELECT' | 'MULTISELECT' | 'BOOLEAN' | 'DATE' | 'SCALE_1_TO_10';
  clinicalDomain: string;
  isRequired: boolean;
  selectOptions?: string[];
  validationMin?: number;
  validationMax?: number;
  clinicalFlagThreshold?: string;
  guidelineHelpText: string;
}

export const PSYCHIATRIC_COMPREHENSIVE_FIELDS: ClinicalFormField[] = [
  {
    fieldId: 'FLD-PSYC-01',
    fieldLabel: 'Psychiatry Diagnostic Parameter 01',
    fieldType: 'NUMBER',
    clinicalDomain: 'Psychiatry',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 1,
    validationMax: 60,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 01.',
  },
  {
    fieldId: 'FLD-PSYC-02',
    fieldLabel: 'Psychiatry Diagnostic Parameter 02',
    fieldType: 'SELECT',
    clinicalDomain: 'Psychiatry',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 2,
    validationMax: 70,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 02.',
  },
  {
    fieldId: 'FLD-PSYC-03',
    fieldLabel: 'Psychiatry Diagnostic Parameter 03',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Psychiatry',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 3,
    validationMax: 80,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 03.',
  },
  {
    fieldId: 'FLD-PSYC-04',
    fieldLabel: 'Psychiatry Diagnostic Parameter 04',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Psychiatry',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 4,
    validationMax: 90,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 04.',
  },
  {
    fieldId: 'FLD-PSYC-05',
    fieldLabel: 'Psychiatry Diagnostic Parameter 05',
    fieldType: 'TEXT',
    clinicalDomain: 'Psychiatry',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 5,
    validationMax: 100,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 05.',
  },
  {
    fieldId: 'FLD-PSYC-06',
    fieldLabel: 'Psychiatry Diagnostic Parameter 06',
    fieldType: 'NUMBER',
    clinicalDomain: 'Psychiatry',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 6,
    validationMax: 110,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 06.',
  },
  {
    fieldId: 'FLD-PSYC-07',
    fieldLabel: 'Psychiatry Diagnostic Parameter 07',
    fieldType: 'SELECT',
    clinicalDomain: 'Psychiatry',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 7,
    validationMax: 120,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 07.',
  },
  {
    fieldId: 'FLD-PSYC-08',
    fieldLabel: 'Psychiatry Diagnostic Parameter 08',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Psychiatry',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 8,
    validationMax: 130,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 08.',
  },
  {
    fieldId: 'FLD-PSYC-09',
    fieldLabel: 'Psychiatry Diagnostic Parameter 09',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Psychiatry',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 9,
    validationMax: 140,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 09.',
  },
  {
    fieldId: 'FLD-PSYC-10',
    fieldLabel: 'Psychiatry Diagnostic Parameter 10',
    fieldType: 'TEXT',
    clinicalDomain: 'Psychiatry',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 10,
    validationMax: 150,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 10.',
  },
  {
    fieldId: 'FLD-PSYC-11',
    fieldLabel: 'Psychiatry Diagnostic Parameter 11',
    fieldType: 'NUMBER',
    clinicalDomain: 'Psychiatry',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 11,
    validationMax: 160,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 11.',
  },
  {
    fieldId: 'FLD-PSYC-12',
    fieldLabel: 'Psychiatry Diagnostic Parameter 12',
    fieldType: 'SELECT',
    clinicalDomain: 'Psychiatry',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 12,
    validationMax: 170,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 12.',
  },
  {
    fieldId: 'FLD-PSYC-13',
    fieldLabel: 'Psychiatry Diagnostic Parameter 13',
    fieldType: 'BOOLEAN',
    clinicalDomain: 'Psychiatry',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 13,
    validationMax: 180,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 13.',
  },
  {
    fieldId: 'FLD-PSYC-14',
    fieldLabel: 'Psychiatry Diagnostic Parameter 14',
    fieldType: 'SCALE_1_TO_10',
    clinicalDomain: 'Psychiatry',
    isRequired: true,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 14,
    validationMax: 190,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 14.',
  },
  {
    fieldId: 'FLD-PSYC-15',
    fieldLabel: 'Psychiatry Diagnostic Parameter 15',
    fieldType: 'TEXT',
    clinicalDomain: 'Psychiatry',
    isRequired: false,
    selectOptions: ['Normal / Baseline', 'Mild Deviation', 'Moderate Deviation', 'Severe / Urgent Intervention'],
    validationMin: 15,
    validationMax: 200,
    clinicalFlagThreshold: 'Value exceeds standard psychiatry safety limits',
    guidelineHelpText: 'Guideline-directed clinical evaluation criteria for psychiatry parameter 15.',
  },
];

export function getPsychiatricComprehensiveField(id: string): ClinicalFormField | undefined {
  return PSYCHIATRIC_COMPREHENSIVE_FIELDS.find((f) => f.fieldId === id);
}
