// CareMate Enterprise CDS Engine: Arrhythmia Staging & Device Management
// Clinical Practice Guidelines, Algorithmic Rules, and Triage Criteria

export interface SpecialtyClinicalProtocol {
  protocolId: string;
  clinicalTopic: string;
  primaryIndication: string;
  riskCategory: 'LOW' | 'MODERATE' | 'HIGH' | 'CRITICAL_URGENCY';
  initialTriageAction: string;
  diagnosticWorkup: string[];
  pharmacologicIntervention: string;
  nonPharmacologicMeasures: string[];
  criticalMonitoringIntervalMinutes: number;
  dischargeOrEscalationCriteria: string;
  clinicalEvidenceLevel: 'LEVEL_I_RCT' | 'LEVEL_II_COHORT' | 'LEVEL_III_CONSENSUS';
}

export const CARDIAC_ELECTROPHYSIOLOGY_PROTOCOLS: SpecialtyClinicalProtocol[] = [
  {
    protocolId: 'PRT-CAR-001',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 001',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 001.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 001.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CAR-002',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 002',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 002.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 002.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CAR-003',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 003',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 003.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 003.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CAR-004',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 004',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 004.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 004.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CAR-005',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 005',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 005.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 005.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CAR-006',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 006',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 006.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 006.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CAR-007',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 007',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 007.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 007.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CAR-008',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 008',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 008.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 008.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CAR-009',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 009',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 009.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 009.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CAR-010',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 010',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 010.',
    riskCategory: 'CRITICAL_URGENCY',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 010.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CAR-011',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 011',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 011.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 011.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CAR-012',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 012',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 012.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 012.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CAR-013',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 013',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 013.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 013.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CAR-014',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 014',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 014.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 014.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CAR-015',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 015',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 015.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 015.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CAR-016',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 016',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 016.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 016.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CAR-017',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 017',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 017.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 017.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CAR-018',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 018',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 018.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 018.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CAR-019',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 019',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 019.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 019.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CAR-020',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 020',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 020.',
    riskCategory: 'CRITICAL_URGENCY',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 020.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CAR-021',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 021',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 021.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 021.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CAR-022',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 022',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 022.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 022.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CAR-023',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 023',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 023.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 023.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CAR-024',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 024',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 024.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 024.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CAR-025',
    clinicalTopic: 'Electrophysiology Evidence-Based Care Protocol 025',
    primaryIndication: 'Clinical indication for electrophysiology evaluation variant 025.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for electrophysiology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for electrophysiology 025.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
];

export function getCardiacElectrophysiologyProtocol(id: string): SpecialtyClinicalProtocol | undefined {
  return CARDIAC_ELECTROPHYSIOLOGY_PROTOCOLS.find((p) => p.protocolId === id);
}
