// CareMate Enterprise CDS Engine: Intensive Care Hemodynamic & Ventilator Management
// Clinical Practice Guidelines, Algorithmic Rules, and Triage Criteria

export interface SpecialtyClinicalProtocol {
  protocolId: string;
  clinicalTopic: string;
  primaryIndication: string;
  riskCategory: 'LOW' | 'MODERATE' | 'HIGH' | 'CRITICAL_URGENCY';
  initialTriageAction: string;
  diagnosticWorkup: string[];
  pharmacologicIntervention: string;
  nonPharmacologicMeasures: string[];
  criticalMonitoringIntervalMinutes: number;
  dischargeOrEscalationCriteria: string;
  clinicalEvidenceLevel: 'LEVEL_I_RCT' | 'LEVEL_II_COHORT' | 'LEVEL_III_CONSENSUS';
}

export const CRITICAL_CARE_PROTOCOLS: SpecialtyClinicalProtocol[] = [
  {
    protocolId: 'PRT-CRI-001',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 001',
    primaryIndication: 'Clinical indication for critical care evaluation variant 001.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 001.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CRI-002',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 002',
    primaryIndication: 'Clinical indication for critical care evaluation variant 002.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 002.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CRI-003',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 003',
    primaryIndication: 'Clinical indication for critical care evaluation variant 003.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 003.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CRI-004',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 004',
    primaryIndication: 'Clinical indication for critical care evaluation variant 004.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 004.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CRI-005',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 005',
    primaryIndication: 'Clinical indication for critical care evaluation variant 005.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 005.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CRI-006',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 006',
    primaryIndication: 'Clinical indication for critical care evaluation variant 006.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 006.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CRI-007',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 007',
    primaryIndication: 'Clinical indication for critical care evaluation variant 007.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 007.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CRI-008',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 008',
    primaryIndication: 'Clinical indication for critical care evaluation variant 008.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 008.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CRI-009',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 009',
    primaryIndication: 'Clinical indication for critical care evaluation variant 009.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 009.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CRI-010',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 010',
    primaryIndication: 'Clinical indication for critical care evaluation variant 010.',
    riskCategory: 'CRITICAL_URGENCY',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 010.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CRI-011',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 011',
    primaryIndication: 'Clinical indication for critical care evaluation variant 011.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 011.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CRI-012',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 012',
    primaryIndication: 'Clinical indication for critical care evaluation variant 012.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 012.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CRI-013',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 013',
    primaryIndication: 'Clinical indication for critical care evaluation variant 013.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 013.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CRI-014',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 014',
    primaryIndication: 'Clinical indication for critical care evaluation variant 014.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 014.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CRI-015',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 015',
    primaryIndication: 'Clinical indication for critical care evaluation variant 015.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 015.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CRI-016',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 016',
    primaryIndication: 'Clinical indication for critical care evaluation variant 016.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 016.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CRI-017',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 017',
    primaryIndication: 'Clinical indication for critical care evaluation variant 017.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 017.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CRI-018',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 018',
    primaryIndication: 'Clinical indication for critical care evaluation variant 018.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 018.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CRI-019',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 019',
    primaryIndication: 'Clinical indication for critical care evaluation variant 019.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 019.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CRI-020',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 020',
    primaryIndication: 'Clinical indication for critical care evaluation variant 020.',
    riskCategory: 'CRITICAL_URGENCY',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 020.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CRI-021',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 021',
    primaryIndication: 'Clinical indication for critical care evaluation variant 021.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 021.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CRI-022',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 022',
    primaryIndication: 'Clinical indication for critical care evaluation variant 022.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 022.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-CRI-023',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 023',
    primaryIndication: 'Clinical indication for critical care evaluation variant 023.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 023.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-CRI-024',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 024',
    primaryIndication: 'Clinical indication for critical care evaluation variant 024.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 024.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-CRI-025',
    clinicalTopic: 'Critical Care Evidence-Based Care Protocol 025',
    primaryIndication: 'Clinical indication for critical care evaluation variant 025.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for critical care',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for critical care 025.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
];

export function getCriticalCareProtocol(id: string): SpecialtyClinicalProtocol | undefined {
  return CRITICAL_CARE_PROTOCOLS.find((p) => p.protocolId === id);
}
