// CareMate Enterprise CDS Engine: Antimicrobial Stewardship & Pathogen Susceptibility
// Clinical Practice Guidelines, Algorithmic Rules, and Triage Criteria

export interface SpecialtyClinicalProtocol {
  protocolId: string;
  clinicalTopic: string;
  primaryIndication: string;
  riskCategory: 'LOW' | 'MODERATE' | 'HIGH' | 'CRITICAL_URGENCY';
  initialTriageAction: string;
  diagnosticWorkup: string[];
  pharmacologicIntervention: string;
  nonPharmacologicMeasures: string[];
  criticalMonitoringIntervalMinutes: number;
  dischargeOrEscalationCriteria: string;
  clinicalEvidenceLevel: 'LEVEL_I_RCT' | 'LEVEL_II_COHORT' | 'LEVEL_III_CONSENSUS';
}

export const INFECTIOUS_ANTIMICROBIAL_PROTOCOLS: SpecialtyClinicalProtocol[] = [
  {
    protocolId: 'PRT-INF-001',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 001',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 001.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 001.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-INF-002',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 002',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 002.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 002.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-INF-003',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 003',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 003.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 003.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-INF-004',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 004',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 004.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 004.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-INF-005',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 005',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 005.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 005.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-INF-006',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 006',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 006.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 006.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-INF-007',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 007',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 007.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 007.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-INF-008',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 008',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 008.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 008.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-INF-009',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 009',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 009.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 009.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-INF-010',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 010',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 010.',
    riskCategory: 'CRITICAL_URGENCY',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 010.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-INF-011',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 011',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 011.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 011.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-INF-012',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 012',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 012.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 012.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-INF-013',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 013',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 013.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 013.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-INF-014',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 014',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 014.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 014.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-INF-015',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 015',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 015.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 015.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-INF-016',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 016',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 016.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 016.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-INF-017',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 017',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 017.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 017.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-INF-018',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 018',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 018.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 018.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-INF-019',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 019',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 019.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 019.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-INF-020',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 020',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 020.',
    riskCategory: 'CRITICAL_URGENCY',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 020.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-INF-021',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 021',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 021.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 021.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-INF-022',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 022',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 022.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 022.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-INF-023',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 023',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 023.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 023.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-INF-024',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 024',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 024.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 024.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-INF-025',
    clinicalTopic: 'Infectious Disease Evidence-Based Care Protocol 025',
    primaryIndication: 'Clinical indication for infectious disease evaluation variant 025.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for infectious disease',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for infectious disease 025.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
];

export function getInfectiousAntimicrobialProtocol(id: string): SpecialtyClinicalProtocol | undefined {
  return INFECTIOUS_ANTIMICROBIAL_PROTOCOLS.find((p) => p.protocolId === id);
}
