// CareMate Enterprise CDS Engine: Maternal-Fetal Triage & Obstetric Risk Protocols
// Clinical Practice Guidelines, Algorithmic Rules, and Triage Criteria

export interface SpecialtyClinicalProtocol {
  protocolId: string;
  clinicalTopic: string;
  primaryIndication: string;
  riskCategory: 'LOW' | 'MODERATE' | 'HIGH' | 'CRITICAL_URGENCY';
  initialTriageAction: string;
  diagnosticWorkup: string[];
  pharmacologicIntervention: string;
  nonPharmacologicMeasures: string[];
  criticalMonitoringIntervalMinutes: number;
  dischargeOrEscalationCriteria: string;
  clinicalEvidenceLevel: 'LEVEL_I_RCT' | 'LEVEL_II_COHORT' | 'LEVEL_III_CONSENSUS';
}

export const OBSTETRICS_GYNECOLOGY_PROTOCOLS: SpecialtyClinicalProtocol[] = [
  {
    protocolId: 'PRT-OBS-001',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 001',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 001.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 001.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-OBS-002',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 002',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 002.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 002.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-OBS-003',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 003',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 003.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 003.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-OBS-004',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 004',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 004.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 004.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-OBS-005',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 005',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 005.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 005.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-OBS-006',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 006',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 006.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 006.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-OBS-007',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 007',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 007.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 007.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-OBS-008',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 008',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 008.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 008.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-OBS-009',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 009',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 009.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 009.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-OBS-010',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 010',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 010.',
    riskCategory: 'CRITICAL_URGENCY',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 010.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-OBS-011',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 011',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 011.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 011.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-OBS-012',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 012',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 012.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 012.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-OBS-013',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 013',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 013.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 013.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-OBS-014',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 014',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 014.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 014.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-OBS-015',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 015',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 015.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 015.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-OBS-016',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 016',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 016.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 016.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-OBS-017',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 017',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 017.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 017.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-OBS-018',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 018',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 018.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 018.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-OBS-019',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 019',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 019.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 019.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-OBS-020',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 020',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 020.',
    riskCategory: 'CRITICAL_URGENCY',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 020.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-OBS-021',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 021',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 021.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 021.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-OBS-022',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 022',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 022.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 022.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-OBS-023',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 023',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 023.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 023.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-OBS-024',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 024',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 024.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 024.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-OBS-025',
    clinicalTopic: 'Obstetrics & Gynecology Evidence-Based Care Protocol 025',
    primaryIndication: 'Clinical indication for obstetrics & gynecology evaluation variant 025.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for obstetrics & gynecology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for obstetrics & gynecology 025.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
];

export function getObstetricsGynecologyProtocol(id: string): SpecialtyClinicalProtocol | undefined {
  return OBSTETRICS_GYNECOLOGY_PROTOCOLS.find((p) => p.protocolId === id);
}
