// CareMate Enterprise CDS Engine: Toxicologic Ingestion & Antidote Protocols
// Clinical Practice Guidelines, Algorithmic Rules, and Triage Criteria

export interface SpecialtyClinicalProtocol {
  protocolId: string;
  clinicalTopic: string;
  primaryIndication: string;
  riskCategory: 'LOW' | 'MODERATE' | 'HIGH' | 'CRITICAL_URGENCY';
  initialTriageAction: string;
  diagnosticWorkup: string[];
  pharmacologicIntervention: string;
  nonPharmacologicMeasures: string[];
  criticalMonitoringIntervalMinutes: number;
  dischargeOrEscalationCriteria: string;
  clinicalEvidenceLevel: 'LEVEL_I_RCT' | 'LEVEL_II_COHORT' | 'LEVEL_III_CONSENSUS';
}

export const TOXICOLOGY_EMERGENCY_PROTOCOLS: SpecialtyClinicalProtocol[] = [
  {
    protocolId: 'PRT-TOX-001',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 001',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 001.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 001.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-TOX-002',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 002',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 002.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 002.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-TOX-003',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 003',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 003.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 003.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-TOX-004',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 004',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 004.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 004.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-TOX-005',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 005',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 005.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 005.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-TOX-006',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 006',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 006.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 006.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-TOX-007',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 007',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 007.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 007.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-TOX-008',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 008',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 008.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 008.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-TOX-009',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 009',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 009.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 009.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-TOX-010',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 010',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 010.',
    riskCategory: 'CRITICAL_URGENCY',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 010.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-TOX-011',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 011',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 011.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 011.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-TOX-012',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 012',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 012.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 012.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-TOX-013',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 013',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 013.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 013.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-TOX-014',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 014',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 014.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 014.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-TOX-015',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 015',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 015.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 015.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-TOX-016',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 016',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 016.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 016.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-TOX-017',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 017',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 017.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 017.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-TOX-018',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 018',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 018.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 018.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-TOX-019',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 019',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 019.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 019.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-TOX-020',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 020',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 020.',
    riskCategory: 'CRITICAL_URGENCY',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 020.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-TOX-021',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 021',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 021.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 021.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-TOX-022',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 022',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 022.',
    riskCategory: 'MODERATE',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 022.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 45,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_II_COHORT',
  },
  {
    protocolId: 'PRT-TOX-023',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 023',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 023.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 023.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 60,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
  {
    protocolId: 'PRT-TOX-024',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 024',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 024.',
    riskCategory: 'HIGH',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 024.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 15,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_I_RCT',
  },
  {
    protocolId: 'PRT-TOX-025',
    clinicalTopic: 'Medical Toxicology Evidence-Based Care Protocol 025',
    primaryIndication: 'Clinical indication for medical toxicology evaluation variant 025.',
    riskCategory: 'LOW',
    initialTriageAction: 'Immediate baseline assessment, vital sign stabilization, and targeted physical exam.',
    diagnosticWorkup: [
      'Targeted laboratory diagnostic panel for medical toxicology',
      'Baseline 12-lead ECG and continuous cardiorespiratory telemetry',
      'Serum chemistry, renal function, and biomarker evaluation',
    ],
    pharmacologicIntervention: 'Initiate targeted evidence-based therapeutic regimen for medical toxicology 025.',
    nonPharmacologicMeasures: [
      'Continuous pulse oximetry and hemodynamic monitoring',
      'Fluid balance tracking and strict input/output measurement',
      'Patient positioning and airway protection precautions',
    ],
    criticalMonitoringIntervalMinutes: 30,
    dischargeOrEscalationCriteria: 'Clinical stability maintained for > 24 hours without hemodynamic compromise.',
    clinicalEvidenceLevel: 'LEVEL_III_CONSENSUS',
  },
];

export function getToxicologyEmergencyProtocol(id: string): SpecialtyClinicalProtocol | undefined {
  return TOXICOLOGY_EMERGENCY_PROTOCOLS.find((p) => p.protocolId === id);
}
