// CareMate Pediatric Dosing Engine & Safety Calculator
// Weight-based (mg/kg/day) and BSA-based (mg/m2) pediatric pharmacotherapy guidelines

export interface PediatricDosingRule {
  drugCode: string;
  genericName: string;
  therapeuticClass: string;
  minAgeMonths: number;
  maxAgeYears: number;
  dosePerKgMg: number;
  dailyDividedDoses: number;
  maxSingleDoseMg: number;
  maxDailyDoseMg: number;
  administrationRoute: 'ORAL_SUSPENSION' | 'INTRAVENOUS' | 'INTRAMUSCULAR' | 'RECTAL';
  monitoringWarnings: string[];
}

export const PEDIATRIC_DOSING_DATABASE: PediatricDosingRule[] = [
  {
    drugCode: 'PED-DOS-0001',
    genericName: 'Azithromycin Pediatric Form 01',
    therapeuticClass: 'Macrolide Antibiotic',
    minAgeMonths: 2,
    maxAgeYears: 16,
    dosePerKgMg: 11.5,
    dailyDividedDoses: 1,
    maxSingleDoseMg: 255,
    maxDailyDoseMg: 510,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0002',
    genericName: 'Cefdinir Pediatric Form 02',
    therapeuticClass: 'Cephalosporin',
    minAgeMonths: 4,
    maxAgeYears: 16,
    dosePerKgMg: 17.0,
    dailyDividedDoses: 2,
    maxSingleDoseMg: 310,
    maxDailyDoseMg: 620,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0003',
    genericName: 'Ibuprofen Pediatric Form 03',
    therapeuticClass: 'Antipyretic/NSAID',
    minAgeMonths: 6,
    maxAgeYears: 16,
    dosePerKgMg: 14.5,
    dailyDividedDoses: 3,
    maxSingleDoseMg: 415,
    maxDailyDoseMg: 1230,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0004',
    genericName: 'Acetaminophen Pediatric Form 04',
    therapeuticClass: 'Antipyretic/Analgesic',
    minAgeMonths: 8,
    maxAgeYears: 16,
    dosePerKgMg: 21.0,
    dailyDividedDoses: 4,
    maxSingleDoseMg: 520,
    maxDailyDoseMg: 2040,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0005',
    genericName: 'Prednisolone Pediatric Form 05',
    therapeuticClass: 'Corticosteroid',
    minAgeMonths: 10,
    maxAgeYears: 16,
    dosePerKgMg: 1.5,
    dailyDividedDoses: 1,
    maxSingleDoseMg: 65,
    maxDailyDoseMg: 110,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0006',
    genericName: 'Ondansetron Pediatric Form 06',
    therapeuticClass: 'Antiemetic',
    minAgeMonths: 0,
    maxAgeYears: 16,
    dosePerKgMg: 1.65,
    dailyDividedDoses: 3,
    maxSingleDoseMg: 34,
    maxDailyDoseMg: 72,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0007',
    genericName: 'Cephalexin Pediatric Form 07',
    therapeuticClass: 'Antibiotic',
    minAgeMonths: 2,
    maxAgeYears: 16,
    dosePerKgMg: 28.0,
    dailyDividedDoses: 4,
    maxSingleDoseMg: 535,
    maxDailyDoseMg: 2070,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0008',
    genericName: 'Amoxicillin Pediatric Form 08',
    therapeuticClass: 'Antibiotic',
    minAgeMonths: 4,
    maxAgeYears: 16,
    dosePerKgMg: 49.5,
    dailyDividedDoses: 2,
    maxSingleDoseMg: 540,
    maxDailyDoseMg: 1080,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0009',
    genericName: 'Azithromycin Pediatric Form 09',
    therapeuticClass: 'Macrolide Antibiotic',
    minAgeMonths: 6,
    maxAgeYears: 16,
    dosePerKgMg: 16.0,
    dailyDividedDoses: 1,
    maxSingleDoseMg: 295,
    maxDailyDoseMg: 590,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0010',
    genericName: 'Cefdinir Pediatric Form 10',
    therapeuticClass: 'Cephalosporin',
    minAgeMonths: 8,
    maxAgeYears: 16,
    dosePerKgMg: 14.0,
    dailyDividedDoses: 2,
    maxSingleDoseMg: 350,
    maxDailyDoseMg: 700,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0011',
    genericName: 'Ibuprofen Pediatric Form 11',
    therapeuticClass: 'Antipyretic/NSAID',
    minAgeMonths: 10,
    maxAgeYears: 16,
    dosePerKgMg: 11.5,
    dailyDividedDoses: 3,
    maxSingleDoseMg: 455,
    maxDailyDoseMg: 1310,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0012',
    genericName: 'Acetaminophen Pediatric Form 12',
    therapeuticClass: 'Antipyretic/Analgesic',
    minAgeMonths: 0,
    maxAgeYears: 16,
    dosePerKgMg: 18.0,
    dailyDividedDoses: 4,
    maxSingleDoseMg: 560,
    maxDailyDoseMg: 2120,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0013',
    genericName: 'Prednisolone Pediatric Form 13',
    therapeuticClass: 'Corticosteroid',
    minAgeMonths: 2,
    maxAgeYears: 16,
    dosePerKgMg: 6.0,
    dailyDividedDoses: 1,
    maxSingleDoseMg: 105,
    maxDailyDoseMg: 190,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0014',
    genericName: 'Ondansetron Pediatric Form 14',
    therapeuticClass: 'Antiemetic',
    minAgeMonths: 4,
    maxAgeYears: 16,
    dosePerKgMg: 6.15,
    dailyDividedDoses: 3,
    maxSingleDoseMg: 74,
    maxDailyDoseMg: 152,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0015',
    genericName: 'Cephalexin Pediatric Form 15',
    therapeuticClass: 'Antibiotic',
    minAgeMonths: 6,
    maxAgeYears: 16,
    dosePerKgMg: 25.0,
    dailyDividedDoses: 4,
    maxSingleDoseMg: 575,
    maxDailyDoseMg: 2150,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0016',
    genericName: 'Amoxicillin Pediatric Form 16',
    therapeuticClass: 'Antibiotic',
    minAgeMonths: 8,
    maxAgeYears: 16,
    dosePerKgMg: 46.5,
    dailyDividedDoses: 2,
    maxSingleDoseMg: 580,
    maxDailyDoseMg: 1160,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0017',
    genericName: 'Azithromycin Pediatric Form 17',
    therapeuticClass: 'Macrolide Antibiotic',
    minAgeMonths: 10,
    maxAgeYears: 16,
    dosePerKgMg: 13.0,
    dailyDividedDoses: 1,
    maxSingleDoseMg: 335,
    maxDailyDoseMg: 670,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0018',
    genericName: 'Cefdinir Pediatric Form 18',
    therapeuticClass: 'Cephalosporin',
    minAgeMonths: 0,
    maxAgeYears: 16,
    dosePerKgMg: 18.5,
    dailyDividedDoses: 2,
    maxSingleDoseMg: 390,
    maxDailyDoseMg: 780,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0019',
    genericName: 'Ibuprofen Pediatric Form 19',
    therapeuticClass: 'Antipyretic/NSAID',
    minAgeMonths: 2,
    maxAgeYears: 16,
    dosePerKgMg: 16.0,
    dailyDividedDoses: 3,
    maxSingleDoseMg: 495,
    maxDailyDoseMg: 1390,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0020',
    genericName: 'Acetaminophen Pediatric Form 20',
    therapeuticClass: 'Antipyretic/Analgesic',
    minAgeMonths: 4,
    maxAgeYears: 16,
    dosePerKgMg: 15.0,
    dailyDividedDoses: 4,
    maxSingleDoseMg: 600,
    maxDailyDoseMg: 2200,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0021',
    genericName: 'Prednisolone Pediatric Form 21',
    therapeuticClass: 'Corticosteroid',
    minAgeMonths: 6,
    maxAgeYears: 16,
    dosePerKgMg: 3.0,
    dailyDividedDoses: 1,
    maxSingleDoseMg: 145,
    maxDailyDoseMg: 270,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0022',
    genericName: 'Ondansetron Pediatric Form 22',
    therapeuticClass: 'Antiemetic',
    minAgeMonths: 8,
    maxAgeYears: 16,
    dosePerKgMg: 3.15,
    dailyDividedDoses: 3,
    maxSingleDoseMg: 114,
    maxDailyDoseMg: 232,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0023',
    genericName: 'Cephalexin Pediatric Form 23',
    therapeuticClass: 'Antibiotic',
    minAgeMonths: 10,
    maxAgeYears: 16,
    dosePerKgMg: 29.5,
    dailyDividedDoses: 4,
    maxSingleDoseMg: 615,
    maxDailyDoseMg: 2230,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0024',
    genericName: 'Amoxicillin Pediatric Form 24',
    therapeuticClass: 'Antibiotic',
    minAgeMonths: 0,
    maxAgeYears: 16,
    dosePerKgMg: 51.0,
    dailyDividedDoses: 2,
    maxSingleDoseMg: 620,
    maxDailyDoseMg: 1240,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0025',
    genericName: 'Azithromycin Pediatric Form 25',
    therapeuticClass: 'Macrolide Antibiotic',
    minAgeMonths: 2,
    maxAgeYears: 16,
    dosePerKgMg: 10.0,
    dailyDividedDoses: 1,
    maxSingleDoseMg: 375,
    maxDailyDoseMg: 750,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0026',
    genericName: 'Cefdinir Pediatric Form 26',
    therapeuticClass: 'Cephalosporin',
    minAgeMonths: 4,
    maxAgeYears: 16,
    dosePerKgMg: 15.5,
    dailyDividedDoses: 2,
    maxSingleDoseMg: 430,
    maxDailyDoseMg: 860,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0027',
    genericName: 'Ibuprofen Pediatric Form 27',
    therapeuticClass: 'Antipyretic/NSAID',
    minAgeMonths: 6,
    maxAgeYears: 16,
    dosePerKgMg: 13.0,
    dailyDividedDoses: 3,
    maxSingleDoseMg: 535,
    maxDailyDoseMg: 1470,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0028',
    genericName: 'Acetaminophen Pediatric Form 28',
    therapeuticClass: 'Antipyretic/Analgesic',
    minAgeMonths: 8,
    maxAgeYears: 16,
    dosePerKgMg: 19.5,
    dailyDividedDoses: 4,
    maxSingleDoseMg: 640,
    maxDailyDoseMg: 2280,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0029',
    genericName: 'Prednisolone Pediatric Form 29',
    therapeuticClass: 'Corticosteroid',
    minAgeMonths: 10,
    maxAgeYears: 16,
    dosePerKgMg: 7.5,
    dailyDividedDoses: 1,
    maxSingleDoseMg: 185,
    maxDailyDoseMg: 350,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
  {
    drugCode: 'PED-DOS-0030',
    genericName: 'Ondansetron Pediatric Form 30',
    therapeuticClass: 'Antiemetic',
    minAgeMonths: 0,
    maxAgeYears: 16,
    dosePerKgMg: 0.15,
    dailyDividedDoses: 3,
    maxSingleDoseMg: 154,
    maxDailyDoseMg: 312,
    administrationRoute: 'ORAL_SUSPENSION',
    monitoringWarnings: [
      'Ensure accurate weight measurement in kilograms prior to calculating dose',
      'Verify patient renal clearance function if receiving concomitant nephrotoxic therapy',
    ],
  },
];

export function calculatePediatricDose(drugCode: string, weightKg: number): { singleDoseMg: number; dailyDoseMg: number; isExceedingMax: boolean } | null {
  const rule = PEDIATRIC_DOSING_DATABASE.find((r) => r.drugCode === drugCode);
  if (!rule) return null;
  const calculatedDaily = rule.dosePerKgMg * weightKg;
  const cappedDaily = Math.min(calculatedDaily, rule.maxDailyDoseMg);
  const singleDose = Math.min(cappedDaily / rule.dailyDividedDoses, rule.maxSingleDoseMg);
  return {
    singleDoseMg: Number(singleDose.toFixed(1)),
    dailyDoseMg: Number(cappedDaily.toFixed(1)),
    isExceedingMax: calculatedDaily > rule.maxDailyDoseMg,
  };
}
