// CareMate Pharmacogenomics (PGx) & Precision Medicine Decision Support
// CPIC (Clinical Pharmacogenetics Implementation Consortium) Standard Guidelines

export interface PGxClinicalGuideline {
  guidelineId: string;
  geneSymbol: string;
  drugName: string;
  therapeuticArea: string;
  phenotype: 'POOR_METABOLIZER' | 'INTERMEDIATE_METABOLIZER' | 'EXTENSIVE_NORMAL_METABOLIZER' | 'ULTRARAPID_METABOLIZER';
  clinicalImplication: string;
  dosingRecommendation: string;
  evidenceLevel: 'HIGH' | 'MODERATE' | 'PRELIMINARY';
  alternativeTherapy: string;
}

export const PHARMACOGENOMICS_GUIDELINES: PGxClinicalGuideline[] = [
  {
    guidelineId: 'PGX-GDL-0001',
    geneSymbol: 'CYP2D6',
    drugName: 'Tamoxifen Formulation 01',
    therapeuticArea: 'Oncology',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Reduced endoxifen concentration resulting in increased breast cancer recurrence risk.',
    dosingRecommendation: 'Consider alternative endocrine therapy (Aromatase Inhibitor).',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Anastrozole / Letrozole',
  },
  {
    guidelineId: 'PGX-GDL-0002',
    geneSymbol: 'CYP2C19',
    drugName: 'Clopidogrel Formulation 02',
    therapeuticArea: 'Cardiovascular',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Significantly reduced active metabolite formation leading to subtherapeutic platelet inhibition and stent thrombosis.',
    dosingRecommendation: 'Avoid Clopidogrel. Prescribe Prasugrel or Ticagrelor.',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Ticagrelor / Prasugrel',
  },
  {
    guidelineId: 'PGX-GDL-0003',
    geneSymbol: 'CYP2C9',
    drugName: 'Warfarin Formulation 03',
    therapeuticArea: 'Anticoagulation',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Markedly decreased S-warfarin clearance resulting in severe bleeding risk and exaggerated INR response.',
    dosingRecommendation: 'Reduce initial starting dose by 50-70% or prescribe Direct Oral Anticoagulant (DOAC).',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Apixaban / Rivaroxaban',
  },
  {
    guidelineId: 'PGX-GDL-0004',
    geneSymbol: 'TPMT',
    drugName: 'Azathioprine Formulation 04',
    therapeuticArea: 'Immunology',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Fatal myelosuppression and pancytopenia due to elevated thioguanine nucleotide accumulation.',
    dosingRecommendation: 'Reduce dosage by 90% and monitor CBC weekly, or select non-thiopurine immunosuppressant.',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Methotrexate / Mycophenolate',
  },
  {
    guidelineId: 'PGX-GDL-0005',
    geneSymbol: 'HLA-B*5701',
    drugName: 'Abacavir Formulation 05',
    therapeuticArea: 'Infectious Disease',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Immunologically-mediated hypersensitivity reaction presenting with multi-organ failure and fever.',
    dosingRecommendation: 'Contraindicated. Do not initiate Abacavir if HLA-B*5701 allele is positive.',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Tenofovir / Emtricitabine',
  },
  {
    guidelineId: 'PGX-GDL-0006',
    geneSymbol: 'SLCO1B1',
    drugName: 'Simvastatin Formulation 06',
    therapeuticArea: 'Lipid Lowering',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Elevated systemic simvastatin exposure causing severe myopathy and rhabdomyolysis.',
    dosingRecommendation: 'Prescribe lower dose or switch to alternative statin (Rosuvastatin, Pravastatin).',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Rosuvastatin / Pravastatin',
  },
  {
    guidelineId: 'PGX-GDL-0007',
    geneSymbol: 'CYP2D6',
    drugName: 'Codeine Formulation 07',
    therapeuticArea: 'Analgesia',
    phenotype: 'ULTRARAPID_METABOLIZER',
    clinicalImplication: 'Increased morphine formation resulting in life-threatening opioid toxicity and respiratory depression.',
    dosingRecommendation: 'Avoid Codeine. Use alternative non-CYP2D6 metabolized analgesic (Morphine, Hydromorphone).',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Morphine / Non-opioid',
  },
  {
    guidelineId: 'PGX-GDL-0008',
    geneSymbol: 'CYP2D6',
    drugName: 'Tamoxifen Formulation 08',
    therapeuticArea: 'Oncology',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Reduced endoxifen concentration resulting in increased breast cancer recurrence risk.',
    dosingRecommendation: 'Consider alternative endocrine therapy (Aromatase Inhibitor).',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Anastrozole / Letrozole',
  },
  {
    guidelineId: 'PGX-GDL-0009',
    geneSymbol: 'CYP2C19',
    drugName: 'Clopidogrel Formulation 09',
    therapeuticArea: 'Cardiovascular',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Significantly reduced active metabolite formation leading to subtherapeutic platelet inhibition and stent thrombosis.',
    dosingRecommendation: 'Avoid Clopidogrel. Prescribe Prasugrel or Ticagrelor.',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Ticagrelor / Prasugrel',
  },
  {
    guidelineId: 'PGX-GDL-0010',
    geneSymbol: 'CYP2C9',
    drugName: 'Warfarin Formulation 10',
    therapeuticArea: 'Anticoagulation',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Markedly decreased S-warfarin clearance resulting in severe bleeding risk and exaggerated INR response.',
    dosingRecommendation: 'Reduce initial starting dose by 50-70% or prescribe Direct Oral Anticoagulant (DOAC).',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Apixaban / Rivaroxaban',
  },
  {
    guidelineId: 'PGX-GDL-0011',
    geneSymbol: 'TPMT',
    drugName: 'Azathioprine Formulation 11',
    therapeuticArea: 'Immunology',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Fatal myelosuppression and pancytopenia due to elevated thioguanine nucleotide accumulation.',
    dosingRecommendation: 'Reduce dosage by 90% and monitor CBC weekly, or select non-thiopurine immunosuppressant.',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Methotrexate / Mycophenolate',
  },
  {
    guidelineId: 'PGX-GDL-0012',
    geneSymbol: 'HLA-B*5701',
    drugName: 'Abacavir Formulation 12',
    therapeuticArea: 'Infectious Disease',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Immunologically-mediated hypersensitivity reaction presenting with multi-organ failure and fever.',
    dosingRecommendation: 'Contraindicated. Do not initiate Abacavir if HLA-B*5701 allele is positive.',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Tenofovir / Emtricitabine',
  },
  {
    guidelineId: 'PGX-GDL-0013',
    geneSymbol: 'SLCO1B1',
    drugName: 'Simvastatin Formulation 13',
    therapeuticArea: 'Lipid Lowering',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Elevated systemic simvastatin exposure causing severe myopathy and rhabdomyolysis.',
    dosingRecommendation: 'Prescribe lower dose or switch to alternative statin (Rosuvastatin, Pravastatin).',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Rosuvastatin / Pravastatin',
  },
  {
    guidelineId: 'PGX-GDL-0014',
    geneSymbol: 'CYP2D6',
    drugName: 'Codeine Formulation 14',
    therapeuticArea: 'Analgesia',
    phenotype: 'ULTRARAPID_METABOLIZER',
    clinicalImplication: 'Increased morphine formation resulting in life-threatening opioid toxicity and respiratory depression.',
    dosingRecommendation: 'Avoid Codeine. Use alternative non-CYP2D6 metabolized analgesic (Morphine, Hydromorphone).',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Morphine / Non-opioid',
  },
  {
    guidelineId: 'PGX-GDL-0015',
    geneSymbol: 'CYP2D6',
    drugName: 'Tamoxifen Formulation 15',
    therapeuticArea: 'Oncology',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Reduced endoxifen concentration resulting in increased breast cancer recurrence risk.',
    dosingRecommendation: 'Consider alternative endocrine therapy (Aromatase Inhibitor).',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Anastrozole / Letrozole',
  },
  {
    guidelineId: 'PGX-GDL-0016',
    geneSymbol: 'CYP2C19',
    drugName: 'Clopidogrel Formulation 16',
    therapeuticArea: 'Cardiovascular',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Significantly reduced active metabolite formation leading to subtherapeutic platelet inhibition and stent thrombosis.',
    dosingRecommendation: 'Avoid Clopidogrel. Prescribe Prasugrel or Ticagrelor.',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Ticagrelor / Prasugrel',
  },
  {
    guidelineId: 'PGX-GDL-0017',
    geneSymbol: 'CYP2C9',
    drugName: 'Warfarin Formulation 17',
    therapeuticArea: 'Anticoagulation',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Markedly decreased S-warfarin clearance resulting in severe bleeding risk and exaggerated INR response.',
    dosingRecommendation: 'Reduce initial starting dose by 50-70% or prescribe Direct Oral Anticoagulant (DOAC).',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Apixaban / Rivaroxaban',
  },
  {
    guidelineId: 'PGX-GDL-0018',
    geneSymbol: 'TPMT',
    drugName: 'Azathioprine Formulation 18',
    therapeuticArea: 'Immunology',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Fatal myelosuppression and pancytopenia due to elevated thioguanine nucleotide accumulation.',
    dosingRecommendation: 'Reduce dosage by 90% and monitor CBC weekly, or select non-thiopurine immunosuppressant.',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Methotrexate / Mycophenolate',
  },
  {
    guidelineId: 'PGX-GDL-0019',
    geneSymbol: 'HLA-B*5701',
    drugName: 'Abacavir Formulation 19',
    therapeuticArea: 'Infectious Disease',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Immunologically-mediated hypersensitivity reaction presenting with multi-organ failure and fever.',
    dosingRecommendation: 'Contraindicated. Do not initiate Abacavir if HLA-B*5701 allele is positive.',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Tenofovir / Emtricitabine',
  },
  {
    guidelineId: 'PGX-GDL-0020',
    geneSymbol: 'SLCO1B1',
    drugName: 'Simvastatin Formulation 20',
    therapeuticArea: 'Lipid Lowering',
    phenotype: 'POOR_METABOLIZER',
    clinicalImplication: 'Elevated systemic simvastatin exposure causing severe myopathy and rhabdomyolysis.',
    dosingRecommendation: 'Prescribe lower dose or switch to alternative statin (Rosuvastatin, Pravastatin).',
    evidenceLevel: 'HIGH',
    alternativeTherapy: 'Rosuvastatin / Pravastatin',
  },
];

export function getPGxGuideline(gene: string, drug: string): PGxClinicalGuideline | undefined {
  return PHARMACOGENOMICS_GUIDELINES.find(
    (g) => g.geneSymbol.toLowerCase() === gene.toLowerCase() && g.drugName.toLowerCase().includes(drug.toLowerCase())
  );
}
